export const enCountries = [
  { code: 'AF', label: 'Afghanistan' },
  { code: 'AX', label: 'Aland Islands' },
  { code: 'AL', label: 'Albania' },
  { code: 'DZ', label: 'Algeria' },
  { code: 'AS', label: 'American Samoa' },
  { code: 'AD', label: 'Andorra' },
  { code: 'AO', label: 'Angola' },
  { code: 'AI', label: 'Anguilla' },
  { code: 'AQ', label: 'Antarctica' },
  { code: 'AG', label: 'Antigua And Barbuda' },
  { code: 'AR', label: 'Argentina' },
  { code: 'AM', label: 'Armenia' },
  { code: 'AW', label: 'Aruba' },
  { code: 'AU', label: 'Australia' },
  { code: 'AT', label: 'Austria' },
  { code: 'AZ', label: 'Azerbaijan' },
  { code: 'BS', label: 'Bahamas' },
  { code: 'BH', label: 'Bahrain' },
  { code: 'BD', label: 'Bangladesh' },
  { code: 'BB', label: 'Barbados' },
  { code: 'BY', label: 'Belarus' },
  { code: 'BE', label: 'Belgium' },
  { code: 'BZ', label: 'Belize' },
  { code: 'BJ', label: 'Benin' },
  { code: 'BM', label: 'Bermuda' },
  { code: 'BT', label: 'Bhutan' },
  { code: 'BO', label: 'Bolivia' },
  { code: 'BQ', label: 'Bonaire, Sint Eustatius and Saba' },
  { code: 'BA', label: 'Bosnia And Herzegovina' },
  { code: 'BW', label: 'Botswana' },
  { code: 'BV', label: 'Bouvet Island' },
  { code: 'BR', label: 'Brazil' },
  { code: 'IO', label: 'British Indian Ocean Territory' },
  { code: 'BN', label: 'Brunei Darussalam' },
  { code: 'BG', label: 'Bulgaria' },
  { code: 'BF', label: 'Burkina Faso' },
  { code: 'BI', label: 'Burundi' },
  { code: 'KH', label: 'Cambodia' },
  { code: 'CM', label: 'Cameroon' },
  { code: 'CA', label: 'Canada' },
  { code: 'CV', label: 'Cape Verde' },
  { code: 'KY', label: 'Cayman Islands' },
  { code: 'CF', label: 'Central African Republic' },
  { code: 'TD', label: 'Chad' },
  { code: 'CL', label: 'Chile' },
  { code: 'CN', label: 'China' },
  { code: 'CX', label: 'Christmas Island' },
  { code: 'CC', label: 'Cocos (Keeling) Islands' },
  { code: 'CO', label: 'Colombia' },
  { code: 'KM', label: 'Comoros' },
  { code: 'CG', label: 'Congo' },
  { code: 'CD', label: 'Congo}, Democratic Republic' },
  { code: 'CK', label: 'Cook Islands' },
  { code: 'CR', label: 'Costa Rica' },
  { code: 'CI', label: `Cote D'Ivoire` },
  { code: 'HR', label: 'Croatia' },
  { code: 'CU', label: 'Cuba' },
  { code: 'CY', label: 'Cyprus' },
  { code: 'CZ', label: 'Czech Republic' },
  { code: 'DK', label: 'Denmark' },
  { code: 'DJ', label: 'Djibouti' },
  { code: 'DM', label: 'Dominica' },
  { code: 'DO', label: 'Dominican Republic' },
  { code: 'EC', label: 'Ecuador' },
  { code: 'EG', label: 'Egypt' },
  { code: 'SV', label: 'El Salvador' },
  { code: 'GQ', label: 'Equatorial Guinea' },
  { code: 'ER', label: 'Eritrea' },
  { code: 'EE', label: 'Estonia' },
  { code: 'ET', label: 'Ethiopia' },
  { code: 'FK', label: 'Falkland Islands (Malvinas)' },
  { code: 'FO', label: 'Faroe Islands' },
  { code: 'FJ', label: 'Fiji' },
  { code: 'FI', label: 'Finland' },
  { code: 'FR', label: 'France' },
  { code: 'GF', label: 'French Guiana' },
  { code: 'PF', label: 'French Polynesia' },
  { code: 'TF', label: 'French Southern Territories' },
  { code: 'GA', label: 'Gabon' },
  { code: 'GM', label: 'Gambia' },
  { code: 'GE', label: 'Georgia' },
  { code: 'DE', label: 'Germany' },
  { code: 'GH', label: 'Ghana' },
  { code: 'GI', label: 'Gibraltar' },
  { code: 'GR', label: 'Greece' },
  { code: 'GL', label: 'Greenland' },
  { code: 'GD', label: 'Grenada' },
  { code: 'GP', label: 'Guadeloupe' },
  { code: 'GU', label: 'Guam' },
  { code: 'GT', label: 'Guatemala' },
  { code: 'GG', label: 'Guernsey' },
  { code: 'GN', label: 'Guinea' },
  { code: 'GW', label: 'Guinea-Bissau' },
  { code: 'GY', label: 'Guyana' },
  { code: 'HT', label: 'Haiti' },
  { code: 'HM', label: 'Heard Island & Mcdonald Islands' },
  { code: 'VA', label: 'Holy See (Vatican City State)' },
  { code: 'HN', label: 'Honduras' },
  { code: 'HK', label: 'Hong Kong' },
  { code: 'HU', label: 'Hungary' },
  { code: 'IS', label: 'Iceland' },
  { code: 'IN', label: 'India' },
  { code: 'ID', label: 'Indonesia' },
  { code: 'IR', label: 'Iran}, Islamic Republic Of' },
  { code: 'IQ', label: 'Iraq' },
  { code: 'IE', label: 'Ireland' },
  { code: 'IM', label: 'Isle Of Man' },
  { code: 'IL', label: 'Israel' },
  { code: 'IT', label: 'Italy' },
  { code: 'JM', label: 'Jamaica' },
  { code: 'JP', label: 'Japan' },
  { code: 'JE', label: 'Jersey' },
  { code: 'JO', label: 'Jordan' },
  { code: 'KZ', label: 'Kazakhstan' },
  { code: 'KE', label: 'Kenya' },
  { code: 'KI', label: 'Kiribati' },
  { code: 'KR', label: 'Korea (Republic of)' },
  { code: 'KP', label: `Korea (Democratic People's Republic of)` },
  { code: 'KW', label: 'Kuwait' },
  { code: 'KG', label: 'Kyrgyzstan' },
  { code: 'LA', label: `Lao People's Democratic Republic` },
  { code: 'LV', label: 'Latvia' },
  { code: 'LB', label: 'Lebanon' },
  { code: 'LS', label: 'Lesotho' },
  { code: 'LR', label: 'Liberia' },
  { code: 'LY', label: 'Libyan Arab Jamahiriya' },
  { code: 'LI', label: 'Liechtenstein' },
  { code: 'LT', label: 'Lithuania' },
  { code: 'LU', label: 'Luxembourg' },
  { code: 'MO', label: 'Macao' },
  { code: 'MK', label: 'Macedonia' },
  { code: 'MG', label: 'Madagascar' },
  { code: 'MW', label: 'Malawi' },
  { code: 'MY', label: 'Malaysia' },
  { code: 'MV', label: 'Maldives' },
  { code: 'ML', label: 'Mali' },
  { code: 'MT', label: 'Malta' },
  { code: 'MH', label: 'Marshall Islands' },
  { code: 'MQ', label: 'Martinique' },
  { code: 'MR', label: 'Mauritania' },
  { code: 'MU', label: 'Mauritius' },
  { code: 'YT', label: 'Mayotte' },
  { code: 'MX', label: 'Mexico' },
  { code: 'FM', label: 'Micronesia}, Federated States Of' },
  { code: 'MD', label: 'Moldova' },
  { code: 'MC', label: 'Monaco' },
  { code: 'MN', label: 'Mongolia' },
  { code: 'ME', label: 'Montenegro' },
  { code: 'MS', label: 'Montserrat' },
  { code: 'MA', label: 'Morocco' },
  { code: 'MZ', label: 'Mozambique' },
  { code: 'MM', label: 'Myanmar' },
  { code: 'NA', label: 'Namibia' },
  { code: 'NR', label: 'Nauru' },
  { code: 'NP', label: 'Nepal' },
  { code: 'NL', label: 'Netherlands' },
  { code: 'NC', label: 'New Caledonia' },
  { code: 'NZ', label: 'New Zealand' },
  { code: 'NI', label: 'Nicaragua' },
  { code: 'NE', label: 'Niger' },
  { code: 'NG', label: 'Nigeria' },
  { code: 'NU', label: 'Niue' },
  { code: 'NF', label: 'Norfolk Island' },
  { code: 'MP', label: 'Northern Mariana Islands' },
  { code: 'NO', label: 'Norway' },
  { code: 'OM', label: 'Oman' },
  { code: 'PK', label: 'Pakistan' },
  { code: 'PW', label: 'Palau' },
  { code: 'PS', label: 'Palestinian Territory}, Occupied' },
  { code: 'PA', label: 'Panama' },
  { code: 'PG', label: 'Papua New Guinea' },
  { code: 'PY', label: 'Paraguay' },
  { code: 'PE', label: 'Peru' },
  { code: 'PH', label: 'Philippines' },
  { code: 'PN', label: 'Pitcairn' },
  { code: 'PL', label: 'Poland' },
  { code: 'PT', label: 'Portugal' },
  { code: 'PR', label: 'Puerto Rico' },
  { code: 'QA', label: 'Qatar' },
  { code: 'RE', label: 'Reunion' },
  { code: 'RO', label: 'Romania' },
  { code: 'RU', label: 'Russian Federation' },
  { code: 'RW', label: 'Rwanda' },
  { code: 'BL', label: 'Saint Barthelemy' },
  { code: 'SH', label: 'Saint Helena' },
  { code: 'KN', label: 'Saint Kitts And Nevis' },
  { code: 'LC', label: 'Saint Lucia' },
  { code: 'MF', label: 'Saint Martin (France)' },
  { code: 'SX', label: 'Saint Martin' },
  { code: 'PM', label: 'Saint Pierre And Miquelon' },
  { code: 'VC', label: 'Saint Vincent And Grenadines' },
  { code: 'WS', label: 'Samoa' },
  { code: 'SM', label: 'San Marino' },
  { code: 'ST', label: 'Sao Tome And Principe' },
  { code: 'SA', label: 'Saudi Arabia' },
  { code: 'SN', label: 'Senegal' },
  { code: 'RS', label: 'Serbia' },
  { code: 'SC', label: 'Seychelles' },
  { code: 'SL', label: 'Sierra Leone' },
  { code: 'SG', label: 'Singapore' },
  { code: 'SK', label: 'Slovakia' },
  { code: 'SI', label: 'Slovenia' },
  { code: 'SB', label: 'Solomon Islands' },
  { code: 'SO', label: 'Somalia' },
  { code: 'ZA', label: 'South Africa' },
  { code: 'GS', label: 'South Georgia And Sandwich Isl.' },
  { code: 'SS', label: 'South Sudan' },
  { code: 'ES', label: 'Spain' },
  { code: 'LK', label: 'Sri Lanka' },
  { code: 'SD', label: 'Sudan' },
  { code: 'SR', label: 'Suriname' },
  { code: 'SJ', label: 'Svalbard And Jan Mayen' },
  { code: 'SZ', label: 'Swaziland' },
  { code: 'SE', label: 'Sweden' },
  { code: 'CH', label: 'Switzerland' },
  { code: 'SY', label: 'Syrian Arab Republic' },
  { code: 'TW', label: 'Taiwan' },
  { code: 'TJ', label: 'Tajikistan' },
  { code: 'TZ', label: 'Tanzania' },
  { code: 'TH', label: 'Thailand' },
  { code: 'TL', label: 'Timor-Leste' },
  { code: 'TG', label: 'Togo' },
  { code: 'TK', label: 'Tokelau' },
  { code: 'TO', label: 'Tonga' },
  { code: 'TT', label: 'Trinidad And Tobago' },
  { code: 'TN', label: 'Tunisia' },
  { code: 'TR', label: 'Turkey' },
  { code: 'TM', label: 'Turkmenistan' },
  { code: 'TC', label: 'Turks And Caicos Islands' },
  { code: 'TV', label: 'Tuvalu' },
  { code: 'UG', label: 'Uganda' },
  { code: 'UA', label: 'Ukraine' },
  { code: 'AE', label: 'United Arab Emirates' },
  { code: 'GB', label: 'United Kingdom' },
  { code: 'US', label: 'United States' },
  { code: 'UM', label: 'United States Outlying Islands' },
  { code: 'UY', label: 'Uruguay' },
  { code: 'UZ', label: 'Uzbekistan' },
  { code: 'VU', label: 'Vanuatu' },
  { code: 'VE', label: 'Venezuela' },
  { code: 'VN', label: 'Vietnam' },
  { code: 'VG', label: 'Virgin Islands}, British' },
  { code: 'VI', label: 'Virgin Islands}, U.S.' },
  { code: 'WF', label: 'Wallis And Futuna' },
  { code: 'EH', label: 'Western Sahara' },
  { code: 'YE', label: 'Yemen' },
  { code: 'ZM', label: 'Zambia' },
  { code: 'ZW', label: 'Zimbabwe' },
];

export const esCountries = [
  { code: 'AD', label: 'Andorra' },
  { code: 'AE', label: 'Emiratos Árabes Unidos' },
  { code: 'AF', label: 'Afganistán' },
  { code: 'AG', label: 'Antigua y Barbuda' },
  { code: 'AI', label: 'Anguila' },
  { code: 'AL', label: 'Albania' },
  { code: 'AM', label: 'Armenia' },
  { code: 'AO', label: 'Angola' },
  { code: 'AQ', label: 'Antártida' },
  { code: 'AR', label: 'Argentina' },
  { code: 'AS', label: 'Samoa Americana' },
  { code: 'AT', label: 'Austria' },
  { code: 'AU', label: 'Australia' },
  { code: 'AW', label: 'Aruba' },
  { code: 'AX', label: 'Islas de Åland' },
  { code: 'AZ', label: 'Azerbaiyán' },
  { code: 'BA', label: 'Bosnia y Herzegovina' },
  { code: 'BB', label: 'Barbados' },
  { code: 'BD', label: 'Bangladesh' },
  { code: 'BE', label: 'Bélgica' },
  { code: 'BF', label: 'Burkina Faso' },
  { code: 'BG', label: 'Bulgaria' },
  { code: 'BH', label: 'Bahrein' },
  { code: 'BI', label: 'Burundi' },
  { code: 'BJ', label: 'Benín' },
  { code: 'BL', label: 'San Bartolomé' },
  { code: 'BM', label: 'Islas Bermudas' },
  { code: 'BN', label: 'Brunéi' },
  { code: 'BO', label: 'Bolivia' },
  { code: 'BQ', label: 'Bonaire, San Eustaquio y Saba' },
  { code: 'BR', label: 'Brasil' },
  { code: 'BS', label: 'Bahamas' },
  { code: 'BT', label: 'Bhután' },
  { code: 'BV', label: 'Isla Bouvet' },
  { code: 'BW', label: 'Botsuana' },
  { code: 'BY', label: 'Bielorrusia' },
  { code: 'BZ', label: 'Belice' },
  { code: 'CA', label: 'Canadá' },
  { code: 'CC', label: 'Islas Cocos (Keeling)' },
  { code: 'CD', label: 'República Democrática del Congo' },
  { code: 'CF', label: 'República Centroafricana' },
  { code: 'CG', label: 'República del Congo' },
  { code: 'CH', label: 'Suiza' },
  { code: 'CI', label: 'Costa de Marfil' },
  { code: 'CK', label: 'Islas Cook' },
  { code: 'CL', label: 'Chile' },
  { code: 'CM', label: 'Camerún' },
  { code: 'CN', label: 'China' },
  { code: 'CO', label: 'Colombia' },
  { code: 'CR', label: 'Costa Rica' },
  { code: 'CU', label: 'Cuba' },
  { code: 'CV', label: 'Cabo Verde' },
  { code: 'CW', label: 'Curazao' },
  { code: 'CX', label: 'Isla de Navidad' },
  { code: 'CY', label: 'Chipre' },
  { code: 'CZ', label: 'República Checa' },
  { code: 'DE', label: 'Alemania' },
  { code: 'DJ', label: 'Yibuti' },
  { code: 'DK', label: 'Dinamarca' },
  { code: 'DM', label: 'Dominica' },
  { code: 'DO', label: 'República Dominicana' },
  { code: 'DZ', label: 'Argelia' },
  { code: 'EC', label: 'Ecuador' },
  { code: 'EE', label: 'Estonia' },
  { code: 'EG', label: 'Egipto' },
  { code: 'EH', label: 'Sahara Occidental' },
  { code: 'ER', label: 'Eritrea' },
  { code: 'ES', label: 'España' },
  { code: 'ET', label: 'Etiopía' },
  { code: 'FI', label: 'Finlandia' },
  { code: 'FJ', label: 'Fiyi' },
  { code: 'FK', label: 'Islas Malvinas' },
  { code: 'FM', label: 'Micronesia' },
  { code: 'FO', label: 'Islas Feroe' },
  { code: 'FR', label: 'Francia' },
  { code: 'GA', label: 'Gabón' },
  { code: 'GB', label: 'Reino Unido de Gran Bretaña e Irlanda del Norte' },
  { code: 'GD', label: 'Granada' },
  { code: 'GE', label: 'Georgia' },
  { code: 'GF', label: 'Guayana Francesa' },
  { code: 'GG', label: 'Guernsey' },
  { code: 'GH', label: 'Ghana' },
  { code: 'GI', label: 'Gibraltar' },
  { code: 'GL', label: 'Groenlandia' },
  { code: 'GM', label: 'Gambia' },
  { code: 'GN', label: 'Guinea' },
  { code: 'GP', label: 'Guadalupe' },
  { code: 'GQ', label: 'Guinea Ecuatorial' },
  { code: 'GR', label: 'Grecia' },
  { code: 'GS', label: 'Islas Georgias del Sur y Sandwich del Sur' },
  { code: 'GT', label: 'Guatemala' },
  { code: 'GU', label: 'Guam' },
  { code: 'GW', label: 'Guinea-Bissau' },
  { code: 'GY', label: 'Guyana' },
  { code: 'HK', label: 'Hong kong' },
  { code: 'HM', label: 'Islas Heard y McDonald' },
  { code: 'HN', label: 'Honduras' },
  { code: 'HR', label: 'Croacia' },
  { code: 'HT', label: 'Haití' },
  { code: 'HU', label: 'Hungría' },
  { code: 'ID', label: 'Indonesia' },
  { code: 'IE', label: 'Irlanda' },
  { code: 'IL', label: 'Israel' },
  { code: 'IM', label: 'Isla de Man' },
  { code: 'IN', label: 'India' },
  { code: 'IO', label: 'Territorio Británico del Océano Índico' },
  { code: 'IQ', label: 'Irak' },
  { code: 'IR', label: 'Irán' },
  { code: 'IS', label: 'Islandia' },
  { code: 'IT', label: 'Italia' },
  { code: 'JE', label: 'Jersey' },
  { code: 'JM', label: 'Jamaica' },
  { code: 'JO', label: 'Jordania' },
  { code: 'JP', label: 'Japón' },
  { code: 'KE', label: 'Kenia' },
  { code: 'KG', label: 'Kirguistán' },
  { code: 'KH', label: 'Camboya' },
  { code: 'KI', label: 'Kiribati' },
  { code: 'KM', label: 'Comoras' },
  { code: 'KN', label: 'San Cristóbal y Nieves' },
  { code: 'KP', label: 'Corea del Norte' },
  { code: 'KR', label: 'Corea del Sur' },
  { code: 'KW', label: 'Kuwait' },
  { code: 'KY', label: 'Islas Caimán' },
  { code: 'KZ', label: 'Kazajistán' },
  { code: 'LA', label: 'Laos' },
  { code: 'LB', label: 'Líbano' },
  { code: 'LC', label: 'Santa Lucía' },
  { code: 'LI', label: 'Liechtenstein' },
  { code: 'LK', label: 'Sri lanka' },
  { code: 'LR', label: 'Liberia' },
  { code: 'LS', label: 'Lesoto' },
  { code: 'LT', label: 'Lituania' },
  { code: 'LU', label: 'Luxemburgo' },
  { code: 'LV', label: 'Letonia' },
  { code: 'LY', label: 'Libia' },
  { code: 'MA', label: 'Marruecos' },
  { code: 'MC', label: 'Mónaco' },
  { code: 'MD', label: 'Moldavia' },
  { code: 'ME', label: 'Montenegro' },
  { code: 'MF', label: 'San Martín (Francia)' },
  { code: 'MG', label: 'Madagascar' },
  { code: 'MH', label: 'Islas Marshall' },
  { code: 'MK', label: 'Macedônia' },
  { code: 'ML', label: 'Mali' },
  { code: 'MM', label: 'Birmania' },
  { code: 'MN', label: 'Mongolia' },
  { code: 'MO', label: 'Macao' },
  { code: 'MP', label: 'Islas Marianas del Norte' },
  { code: 'MQ', label: 'Martinica' },
  { code: 'MR', label: 'Mauritania' },
  { code: 'MS', label: 'Montserrat' },
  { code: 'MT', label: 'Malta' },
  { code: 'MU', label: 'Mauricio' },
  { code: 'MV', label: 'Islas Maldivas' },
  { code: 'MW', label: 'Malawi' },
  { code: 'MX', label: 'México' },
  { code: 'MY', label: 'Malasia' },
  { code: 'MZ', label: 'Mozambique' },
  { code: 'NA', label: 'Namibia' },
  { code: 'NC', label: 'Nueva Caledonia' },
  { code: 'NE', label: 'Niger' },
  { code: 'NF', label: 'Isla Norfolk' },
  { code: 'NG', label: 'Nigeria' },
  { code: 'NI', label: 'Nicaragua' },
  { code: 'NL', label: 'Países Bajos' },
  { code: 'NO', label: 'Noruega' },
  { code: 'NP', label: 'Nepal' },
  { code: 'NR', label: 'Nauru' },
  { code: 'NU', label: 'Niue' },
  { code: 'NZ', label: 'Nueva Zelanda' },
  { code: 'OM', label: 'Omán' },
  { code: 'PA', label: 'Panamá' },
  { code: 'PE', label: 'Perú' },
  { code: 'PF', label: 'Polinesia Francesa' },
  { code: 'PG', label: 'Papúa Nueva Guinea' },
  { code: 'PH', label: 'Filipinas' },
  { code: 'PK', label: 'Pakistán' },
  { code: 'PL', label: 'Polonia' },
  { code: 'PM', label: 'San Pedro y Miquelón' },
  { code: 'PN', label: 'Islas Pitcairn' },
  { code: 'PR', label: 'Puerto Rico' },
  { code: 'PS', label: 'Palestina' },
  { code: 'PT', label: 'Portugal' },
  { code: 'PW', label: 'Palau' },
  { code: 'PY', label: 'Paraguay' },
  { code: 'QA', label: 'Qatar' },
  { code: 'RE', label: 'Reunión' },
  { code: 'RO', label: 'Rumanía' },
  { code: 'RS', label: 'Serbia' },
  { code: 'RU', label: 'Rusia' },
  { code: 'RW', label: 'Ruanda' },
  { code: 'SA', label: 'Arabia Saudita' },
  { code: 'SB', label: 'Islas Salomón' },
  { code: 'SC', label: 'Seychelles' },
  { code: 'SD', label: 'Sudán' },
  { code: 'SE', label: 'Suecia' },
  { code: 'SG', label: 'Singapur' },
  { code: 'SH', label: 'Santa Elena' },
  { code: 'SI', label: 'Eslovenia' },
  { code: 'SJ', label: 'Svalbard y Jan Mayen' },
  { code: 'SK', label: 'Eslovaquia' },
  { code: 'SL', label: 'Sierra Leona' },
  { code: 'SM', label: 'San Marino' },
  { code: 'SN', label: 'Senegal' },
  { code: 'SO', label: 'Somalia' },
  { code: 'SR', label: 'Surinám' },
  { code: 'SS', label: 'República de Sudán del Sur' },
  { code: 'ST', label: 'Santo Tomé y Príncipe' },
  { code: 'SV', label: 'El Salvador' },
  { code: 'SX', label: 'Sint Maarten' },
  { code: 'SY', label: 'Siria' },
  { code: 'SZ', label: 'Swazilandia' },
  { code: 'TC', label: 'Islas Turcas y Caicos' },
  { code: 'TD', label: 'Chad' },
  { code: 'TF', label: 'Territorios Australes y Antárticas Franceses' },
  { code: 'TG', label: 'Togo' },
  { code: 'TH', label: 'Tailandia' },
  { code: 'TJ', label: 'Tayikistán' },
  { code: 'TK', label: 'Tokelau' },
  { code: 'TL', label: 'Timor Oriental' },
  { code: 'TM', label: 'Turkmenistán' },
  { code: 'TN', label: 'Tunez' },
  { code: 'TO', label: 'Tonga' },
  { code: 'TR', label: 'Turquía' },
  { code: 'TT', label: 'Trinidad y Tobago' },
  { code: 'TV', label: 'Tuvalu' },
  { code: 'TW', label: 'Taiwán' },
  { code: 'TZ', label: 'Tanzania' },
  { code: 'UA', label: 'Ucrania' },
  { code: 'UG', label: 'Uganda' },
  { code: 'UM', label: 'Islas Ultramarinas Menores de Estados Unidos' },
  { code: 'US', label: 'Estados Unidos de América' },
  { code: 'UY', label: 'Uruguay' },
  { code: 'UZ', label: 'Uzbekistán' },
  { code: 'VA', label: 'Ciudad del Vaticano' },
  { code: 'VC', label: 'San Vicente y las Granadinas' },
  { code: 'VE', label: 'Venezuela' },
  { code: 'VG', label: 'Islas Vírgenes Británicas' },
  { code: 'VI', label: 'Islas Vírgenes de los Estados Unidos' },
  { code: 'VN', label: 'Vietnam' },
  { code: 'VU', label: 'Vanuatu' },
  { code: 'WF', label: 'Wallis y Futuna' },
  { code: 'WS', label: 'Samoa' },
  { code: 'YE', label: 'Yemen' },
  { code: 'YT', label: 'Mayotte' },
  { code: 'ZA', label: 'Sudáfrica' },
  { code: 'ZM', label: 'Zambia' },
  { code: 'ZW', label: 'Zimbabue' },
];
