export default [
  {
    code: 'AF',
    label: {
      en: 'Afghanistan',
      hi: 'अफगानिस्तान',
      fr: 'Afghanistan',
      es: 'Afganistán',
      pt: 'Afeganistão',
      de: 'Afghanistan',
    },
  },
  {
    code: 'AX',
    label: {
      en: 'Aland Islands',
      hi: 'आलंद द्वीप',
      fr: 'Îles Åland',
      es: 'Åland',
      pt: 'Ilhas Åland',
      de: 'Åland',
    },
  },
  {
    code: 'AL',
    label: {
      en: 'Albania',
      hi: 'अल्बानिया',
      fr: 'Albanie',
      es: 'Albania',
      pt: 'Albânia',
      de: 'Albanien',
    },
  },
  {
    code: 'DZ',
    label: {
      en: 'Algeria',
      hi: 'अल्जीरिया',
      fr: 'Algérie',
      es: 'Argelia',
      pt: 'Argélia',
      de: 'Algerien',
    },
  },
  {
    code: 'AS',
    label: {
      en: 'American Samoa',
      hi: 'अमेरिकी समोआ',
      fr: 'Samoa américaines',
      es: 'Samoa Americana',
      pt: 'Samoa Americana',
      de: 'Amerikanisch-Samoa',
    },
  },
  {
    code: 'AD',
    label: {
      en: 'Andorra',
      hi: 'आंडोरा',
      fr: 'Andorre',
      es: 'Andorra',
      pt: 'Andorra',
      de: 'Andorra',
    },
  },
  {
    code: 'AO',
    label: {
      en: 'Angola',
      hi: 'अंगोला',
      fr: 'Angola',
      es: 'Angola',
      pt: 'Angola',
      de: 'Angola',
    },
  },
  {
    code: 'AI',
    label: {
      en: 'Anguilla',
      hi: 'एंग्विला',
      fr: 'Anguilla',
      es: 'Anguila',
      pt: 'Anguila',
      de: 'Anguilla',
    },
  },
  {
    code: 'AQ',
    label: {
      en: 'Antarctica',
      hi: 'अंटार्कटिका',
      fr: 'Antarctique',
      es: 'Antártida',
      pt: 'Antártida',
      de: 'Antarktis (Sonderstatus durch Antarktisvertrag)',
    },
  },
  {
    code: 'AG',
    label: {
      en: 'Antigua And Barbuda',
      hi: 'एंटीगुआ और बारबुडा',
      fr: 'Antigua-et-Barbuda',
      es: 'Antigua y Barbuda',
      pt: 'Antígua e Barbuda',
      de: 'Antigua und Barbuda',
    },
  },
  {
    code: 'AR',
    label: {
      en: 'Argentina',
      hi: 'अर्जेंटीना',
      fr: 'Argentine',
      es: 'Argentina',
      pt: 'Argentina',
      de: 'Argentinien',
    },
  },
  {
    code: 'AM',
    label: {
      en: 'Armenia',
      hi: 'आर्मेनिया',
      fr: 'Arménie',
      es: 'Armenia',
      pt: 'Armênia',
      de: 'Armenien',
    },
  },
  {
    code: 'AW',
    label: {
      en: 'Aruba',
      hi: 'अरूबा',
      fr: 'Aruba',
      es: 'Aruba',
      pt: 'Aruba',
      de: 'Aruba',
    },
  },
  {
    code: 'AU',
    label: {
      en: 'Australia',
      hi: 'ऑस्ट्रेलिया',
      fr: 'Australie',
      es: 'Australia',
      pt: 'Austrália',
      de: 'Australien',
    },
  },
  {
    code: 'AT',
    label: {
      en: 'Austria',
      hi: 'ऑस्ट्रिया',
      fr: 'Autriche',
      es: 'Austria',
      pt: 'Áustria',
      de: 'Österreich',
    },
  },
  {
    code: 'AZ',
    label: {
      en: 'Azerbaijan',
      hi: 'अज़रबैजान',
      fr: 'Azerbaïdjan',
      es: 'Azerbaiyán',
      pt: 'Azerbaijão',
      de: 'Aserbaidschan',
    },
  },
  {
    code: 'BS',
    label: {
      en: 'Bahamas',
      hi: 'बहामास',
      fr: 'Bahamas',
      es: 'Bahamas',
      pt: 'Bahamas',
      de: 'Bahamas',
    },
  },
  {
    code: 'BH',
    label: {
      en: 'Bahrain',
      hi: 'बहरीन',
      fr: 'Bahreïn',
      es: 'Baréin',
      pt: 'Barém',
      de: 'Bahrain',
    },
  },
  {
    code: 'BD',
    label: {
      en: 'Bangladesh',
      hi: 'बांग्लादेश',
      fr: 'Bangladesh',
      es: 'Bangladés',
      pt: 'Bangladexe',
      de: 'Bangladesch',
    },
  },
  {
    code: 'BB',
    label: {
      en: 'Barbados',
      hi: 'बारबाडोस',
      fr: 'Barbade',
      es: 'Barbados',
      pt: 'Barbados',
      de: 'Barbados',
    },
  },
  {
    code: 'BY',
    label: {
      en: 'Belarus',
      hi: 'बेलारूस',
      fr: 'Biélorussie',
      es: 'Bielorrusia',
      pt: 'Bielorrússia',
      de: 'Belarus',
    },
  },
  {
    code: 'BE',
    label: {
      en: 'Belgium',
      hi: 'बेल्जियम',
      fr: 'Belgique',
      es: 'Bélgica',
      pt: 'Bélgica',
      de: 'Belgien',
    },
  },
  {
    code: 'BZ',
    label: {
      en: 'Belize',
      hi: 'बेलीज',
      fr: 'Belize',
      es: 'Belice',
      pt: 'Belize',
      de: 'Belize',
    },
  },
  {
    code: 'BJ',
    label: {
      en: 'Benin',
      hi: 'बेनिन',
      fr: 'Bénin',
      es: 'Benín',
      pt: 'Benim',
      de: 'Benin',
    },
  },
  {
    code: 'BM',
    label: {
      en: 'Bermuda',
      hi: 'बरमूडा',
      fr: 'Bermudes',
      es: 'Bermudas',
      pt: 'Bermudas',
      de: 'Bermuda',
    },
  },
  {
    code: 'BT',
    label: {
      en: 'Bhutan',
      hi: 'भूटान',
      fr: 'Bhoutan',
      es: 'Bután',
      pt: 'Butão',
      de: 'Bhutan',
    },
  },
  {
    code: 'BO',
    label: {
      en: 'Bolivia',
      hi: 'बोलीविया',
      fr: 'Bolivie',
      es: 'Bolivia',
      pt: 'Bolívia',
      de: 'Bolivien',
    },
  },
  {
    code: 'BQ',
    label: {
      en: 'Bonaire, Sint Eustatius and Saba',
      hi: 'बोनेयर, सिंट यूस्टेटियस और साबा',
      fr: 'Pays-Bas caribéens',
      es: 'Bonaire, San Eustaquio y Saba',
      pt: 'Países Baixos Caribenhos',
      de: 'Bonaire, Saba, Sint Eustatius',
    },
  },
  {
    code: 'BA',
    label: {
      en: 'Bosnia And Herzegovina',
      hi: 'बोस्निया और हर्जेगोविना',
      fr: 'Bosnie-Herzégovine',
      es: 'Bosnia y Herzegovina',
      pt: 'Bósnia e Herzegovina',
      de: 'Bosnien und Herzegowina',
    },
  },
  {
    code: 'BW',
    label: {
      en: ' Botswana',
      hi: 'बोत्सवाना',
      fr: 'Botswana',
      es: 'Botsuana',
      pt: 'Botsuana',
      de: 'Botswana',
    },
  },
  {
    code: 'BV',
    label: {
      en: 'Bouvet Island',
      hi: 'बोवेट द्वीप',
      fr: 'Île Bouvet',
      es: 'Isla Bouvet',
      pt: 'Ilha Bouvet',
      de: 'Bouvetinsel',
    },
  },
  {
    code: 'BR',
    label: {
      en: 'Brazil',
      hi: 'ब्राज़ील',
      fr: 'Brésil',
      es: 'Brasil',
      pt: 'Brasil',
      de: 'Brasilien',
    },
  },
  {
    code: 'IO',
    label: {
      en: 'British Indian Ocean Territory',
      hi: 'ब्रिटिश हिंद महासागर क्षेत्र',
      fr: "Territoire britannique de l'océan Indien",
      es: 'Territorio Británico del Océano Índico',
      pt: 'Território Britânico do Oceano Índico',
      de: 'Britisches Territorium im Indischen Ozean',
    },
  },
  {
    code: 'BN',
    label: {
      en: 'Brunei Darussalam',
      hi: 'ब्रुनेई दारुस्सलाम',
      fr: 'Brunei',
      es: 'Brunéi',
      pt: 'Brunei',
      de: 'Brunei',
    },
  },
  {
    code: 'BG',
    label: {
      en: 'Bulgaria',
      hi: 'बुल्गारिया',
      fr: 'Bulgarie',
      es: 'Bulgaria',
      pt: 'Bulgária',
      de: 'Bulgarien',
    },
  },
  {
    code: 'BF',
    label: {
      en: 'Burkina Faso',
      hi: 'बुर्किना फासो',
      fr: 'Burkina Faso',
      es: 'Burkina Faso',
      pt: 'Burquina Fasso',
      de: 'Burkina Faso',
    },
  },
  {
    code: 'BI',
    label: {
      en: 'Burundi',
      hi: 'बुरुंडी',
      fr: 'Burundi',
      es: 'Burundi',
      pt: 'Burundi',
      de: 'Burundi',
    },
  },
  {
    code: 'KH',
    label: {
      en: 'Cambodia',
      hi: 'कंबोडिया',
      fr: 'Cambodge',
      es: 'Camboya',
      pt: 'Camboja',
      de: 'Kambodscha',
    },
  },
  {
    code: 'CM',
    label: {
      en: 'Cameroon',
      hi: 'कैमरून',
      fr: 'Cameroun',
      es: 'Camerún',
      pt: 'Camarões',
      de: 'Kamerun',
    },
  },
  {
    code: 'CA',
    label: {
      en: 'Canada',
      hi: 'कनाडा',
      fr: 'Canada',
      es: 'Canadá',
      pt: 'Canadá',
      de: 'Kanada',
    },
  },
  {
    code: 'CV',
    label: {
      en: 'Cape Verde',
      hi: 'केप वर्डे',
      fr: 'Cap-Vert',
      es: 'Cabo Verde',
      pt: 'Cabo Verde',
      de: 'Kap Verde',
    },
  },
  {
    code: 'KY',
    label: {
      en: 'Cayman Islands',
      hi: 'केमैन द्वीप',
      fr: 'Îles Caïmans',
      es: 'Islas Caimán',
      pt: 'Ilhas Caimã',
      de: 'Kaimaninseln',
    },
  },
  {
    code: 'CF',
    label: {
      en: 'Central African Republic',
      hi: 'मध्य अफ़्रीकी गणराज्य',
      fr: 'République centrafricaine',
      es: 'República Centroafricana',
      pt: 'República Centro-Africana',
      de: 'Zentralafrikanische Republik',
    },
  },
  {
    code: 'TD',
    label: {
      en: 'Chad',
      hi: ' चाड',
      fr: 'Tchad',
      es: 'Chad',
      pt: 'Chade',
      de: 'Tschad',
    },
  },
  {
    code: 'CL',
    label: {
      en: 'Chile',
      hi: 'चिली',
      fr: 'Chili',
      es: 'Chile',
      pt: 'Chile',
      de: 'Chile',
    },
  },
  {
    code: 'CN',
    label: {
      en: 'China',
      hi: 'चीन',
      fr: 'Chine',
      es: 'China',
      pt: 'China',
      de: 'China, Volksrepublik',
    },
  },
  {
    code: 'CX',
    label: {
      en: 'Christmas Island',
      hi: 'क्रिसमस द्वीप',
      fr: 'Île Christmas',
      es: 'Isla de Navidad',
      pt: 'Ilha do Natal',
      de: 'Weihnachtsinsel',
    },
  },
  {
    code: 'CC',
    label: {
      en: 'Cocos (Keeling) Islands',
      hi: 'कोकोस (कीलिंग) द्वीप',
      fr: 'Îles Cocos',
      es: 'Islas Cocos',
      pt: 'Ilhas Cocos (Keeling)',
      de: 'Kokosinseln',
    },
  },
  {
    code: 'CO',
    label: {
      en: 'Colombia',
      hi: 'कोलम्बिया',
      fr: 'Colombie',
      es: 'Colombia',
      pt: 'Colômbia',
      de: 'Kolumbien',
    },
  },
  {
    code: 'KM',
    label: {
      en: 'Comoros',
      hi: 'कोमोरोस',
      fr: 'Comores',
      es: 'Comoras',
      pt: 'Comores',
      de: 'Komoren',
    },
  },
  {
    code: 'CG',
    label: {
      en: 'Congo',
      hi: 'कांगो',
      fr: 'République du Congo',
      es: 'República del Congo',
      pt: 'República do Congo',
      de: 'Kongo, Republik',
    },
  },
  {
    code: 'CD',
    label: {
      en: 'Congo}, Democratic Republic',
      hi: 'कांगो, लोकतांत्रिक गणराज्य',
      fr: 'République démocratique du Congo',
      es: 'República Democrática del Congo',
      pt: 'República Democrática do Congo',
      de: 'Kongo, Demokratische Republik',
    },
  },
  {
    code: 'CK',
    label: {
      en: 'Cook Islands',
      hi: 'कुक द्वीप',
      fr: 'Îles Cook',
      es: 'Islas Cook',
      pt: 'Ilhas Cook',
      de: 'Cookinseln',
    },
  },
  {
    code: 'CR',
    label: {
      en: 'Costa Rica',
      hi: 'कोस्टा रिका',
      fr: 'Costa Rica',
      es: 'Costa Rica',
      pt: 'Costa Rica',
      de: 'Costa Rica',
    },
  },
  {
    code: 'CI',
    label: {
      en: "Cote D'Ivoire",
      hi: 'कोटे डी आइवर',
      fr: "Côte d'Ivoire",
      es: 'Costa de Marfil',
      pt: 'Costa do Marfim',
      de: 'Elfenbeinküste',
    },
  },
  {
    code: 'HR',
    label: {
      en: 'Croatia',
      hi: 'क्रोएशिया',
      fr: 'Croatie',
      es: 'Croacia',
      pt: 'Croácia',
      de: 'Kroatien',
    },
  },
  {
    code: 'CU',
    label: {
      en: 'Cuba',
      hi: 'क्यूबा',
      fr: 'Cuba',
      es: 'Cuba',
      pt: 'Cuba',
      de: 'Kuba',
    },
  },
  {
    code: 'CY',
    label: {
      en: 'Cyprus',
      hi: 'साइप्रस',
      fr: 'Chypre',
      es: 'Chipre',
      pt: 'Chipre',
      de: 'Zypern',
    },
  },
  {
    code: 'CZ',
    label: {
      en: 'Czech Republic',
      hi: 'चेक गणराज्य',
      fr: 'République tchèque',
      es: 'República Checa',
      pt: 'República Checa',
      de: 'Tschechische Republik',
    },
  },
  {
    code: 'DK',
    label: {
      en: 'Denmark',
      hi: 'डेनमार्क',
      fr: 'Danemark',
      es: 'Dinamarca',
      pt: 'Dinamarca',
      de: 'Dänemark',
    },
  },
  {
    code: 'DJ',
    label: {
      en: 'Djibouti',
      hi: 'जिबूती',
      fr: 'Djibouti',
      es: 'Yibuti',
      pt: 'Jibuti',
      de: 'Dschibuti',
    },
  },
  {
    code: 'DM',
    label: {
      en: 'Dominica',
      hi: 'डोमिनिका',
      fr: 'Dominique',
      es: 'Dominica',
      pt: 'Dominica',
      de: 'Dominica',
    },
  },
  {
    code: 'DO',
    label: {
      en: 'Dominican Republic',
      hi: 'डोमिनिकन गणराज्य',
      fr: 'République dominicaine',
      es: 'República Dominicana',
      pt: 'República Dominicana',
      de: 'Dominikanische Republik',
    },
  },
  {
    code: 'EC',
    label: {
      en: 'Ecuador',
      hi: 'इक्वाडोर',
      fr: 'Équateur',
      es: 'Ecuador',
      pt: 'Equador',
      de: 'Ecuador',
    },
  },
  {
    code: 'EG',
    label: {
      en: 'Egypt',
      hi: 'मिस्र',
      fr: 'Égypte',
      es: 'Egipto',
      pt: 'Egito',
      de: 'Ägypten',
    },
  },
  {
    code: 'SV',
    label: {
      en: 'El Salvador',
      hi: 'एल सैल्वाडोर',
      fr: 'Salvador',
      es: 'El Salvador',
      pt: 'El Salvador',
      de: 'El Salvador',
    },
  },
  {
    code: 'GQ',
    label: {
      en: 'Equatorial Guinea',
      hi: 'इक्वेटोरियल गिनी',
      fr: 'Guinée équatoriale',
      es: 'Guinea Ecuatorial',
      pt: 'Guiné Equatorial',
      de: 'Äquatorialguinea',
    },
  },
  {
    code: 'ER',
    label: {
      en: 'Eritrea',
      hi: 'एरिट्रिया',
      fr: 'Érythrée',
      es: 'Eritrea',
      pt: 'Eritreia',
      de: 'Eritrea',
    },
  },
  {
    code: 'EE',
    label: {
      en: 'Estonia',
      hi: 'एस्टोनिया',
      fr: 'Estonie',
      es: 'Estonia',
      pt: 'Estónia',
      de: 'Estland',
    },
  },
  {
    code: 'ET',
    label: {
      en: 'Ethiopia',
      hi: 'इथियोपिया',
      fr: 'Éthiopie',
      es: 'Etiopía',
      pt: 'Etiópia',
      de: 'Äthiopien',
    },
  },
  {
    code: 'FK',
    label: {
      en: 'Falkland Islands (Malvinas)',
      hi: 'फ़ॉकलैंड द्वीप (माल्विनास)',
      fr: 'Malouines',
      es: 'Islas Malvinas',
      pt: 'Ilhas Malvinas',
      de: 'Falklandinseln',
    },
  },
  {
    code: 'FO',
    label: {
      en: 'Faroe Islands',
      hi: 'फ़रो द्वीप',
      fr: 'Îles Féroé',
      es: 'Islas Feroe',
      pt: 'Ilhas Feroé',
      de: 'Färöer',
    },
  },
  {
    code: 'FJ',
    label: {
      en: 'Fiji',
      hi: 'फ़िजी',
      fr: 'Fidji',
      es: 'Fiyi',
      pt: 'Fiji',
      de: 'Fidschi',
    },
  },
  {
    code: 'FI',
    label: {
      en: 'Finland',
      hi: 'फ़िनलैंड',
      fr: 'Finlande',
      es: 'Finlandia',
      pt: 'Finlândia',
      de: 'Finnland',
    },
  },
  {
    code: 'FR',
    label: {
      en: 'France',
      hi: 'फ़्रांस',
      fr: 'France',
      es: 'Francia',
      pt: 'França',
      de: 'Frankreich',
    },
  },
  {
    code: 'GF',
    label: {
      en: 'French Guiana',
      hi: 'फ़्रेंच गुयाना',
      fr: 'Guyane',
      es: 'Guayana Francesa',
      pt: 'Guiana Francesa',
      de: 'Französisch-Guayana',
    },
  },
  {
    code: 'PF',
    label: {
      en: 'French Polynesia',
      hi: 'फ़्रेंच पॉलिनेशिया',
      fr: 'Polynésie française',
      es: 'Polinesia Francesa',
      pt: 'Polinésia Francesa',
      de: 'Französisch-Polynesien',
    },
  },
  {
    code: 'TF',
    label: {
      en: 'French Southern Territories',
      hi: 'फ़्रेंच दक्षिणी क्षेत्र',
      fr: 'Terres australes et antarctiques françaises',
      es: 'Tierras Australes y Antárticas Francesas',
      pt: 'Terras Austrais e Antárticas Francesas',
      de: 'Französische Süd- und Antarktisgebiete',
    },
  },
  {
    code: 'GA',
    label: {
      en: 'Gabon',
      hi: 'गैबॉन',
      fr: 'Gabon',
      es: 'Gabón',
      pt: 'Gabão',
      de: 'Gabun',
    },
  },
  {
    code: 'GM',
    label: {
      en: 'Gambia',
      hi: 'गाम्बिया',
      fr: 'Gambie',
      es: 'Gambia',
      pt: 'Gâmbia',
      de: 'Gambia',
    },
  },
  {
    code: 'GE',
    label: {
      en: 'Georgia',
      hi: 'जॉर्जिया',
      fr: 'Géorgie',
      es: 'Georgia',
      pt: 'Geórgia',
      de: 'Georgien',
    },
  },
  {
    code: 'DE',
    label: {
      en: 'Germany',
      hi: 'जर्मनी',
      fr: 'Allemagne',
      es: 'Alemania',
      pt: 'Alemanha',
      de: 'Deutschland',
    },
  },
  {
    code: 'GH',
    label: {
      en: 'Ghana',
      hi: 'घाना',
      fr: 'Ghana',
      es: 'Ghana',
      pt: 'Gana',
      de: 'Ghana',
    },
  },
  {
    code: 'GI',
    label: {
      en: 'Gibraltar',
      hi: 'जिब्राल्टर',
      fr: 'Gibraltar',
      es: 'Gibraltar',
      pt: 'Gibraltar',
      de: 'Gibraltar',
    },
  },
  {
    code: 'GR',
    label: {
      en: 'Greece',
      hi: 'ग्रीस',
      fr: 'Grèce ',
      es: 'Grecia',
      pt: 'Grécia',
      de: 'Griechenland',
    },
  },
  {
    code: 'GL',
    label: {
      en: 'Greenland',
      hi: 'ग्रीनलैंड',
      fr: 'Groenland',
      es: 'Groenlandia',
      pt: 'Gronelândia',
      de: 'Grönland',
    },
  },
  {
    code: 'GD',
    label: {
      en: 'Grenada',
      hi: 'ग्रेनेडा',
      fr: 'Grenade',
      es: 'Granada',
      pt: 'Granada',
      de: 'Grenada',
    },
  },
  {
    code: 'GP',
    label: {
      en: 'Guadeloupe',
      hi: 'ग्वाडेलोप',
      fr: 'Guadeloupe',
      es: 'Guadalupe',
      pt: 'Guadalupe',
      de: 'Guadeloupe',
    },
  },
  {
    code: 'GU',
    label: {
      en: 'Guam',
      hi: 'गुआम',
      fr: 'Guam',
      es: 'Guam',
      pt: 'Guam',
      de: 'Guam',
    },
  },
  {
    code: 'GT',
    label: {
      en: 'Guatemala',
      hi: 'ग्वाटेमाला',
      fr: 'Guatemala',
      es: 'Guatemala',
      pt: 'Guatemala',
      de: 'Guatemala',
    },
  },
  {
    code: 'GG',
    label: {
      en: 'Guernsey',
      hi: 'ग्वेर्नसे',
      fr: 'Guernesey',
      es: 'Guernsey',
      pt: 'Guernsey',
      de: 'Guernsey (Kanalinsel)',
    },
  },
  {
    code: 'GN',
    label: {
      en: 'Guinea',
      hi: 'गिनी',
      fr: 'Guinée',
      es: 'Guinea',
      pt: 'Guiné',
      de: 'Guinea',
    },
  },
  {
    code: 'GW',
    label: {
      en: 'Guinea-Bissau',
      hi: 'गिनी-बिसाऊ',
      fr: 'Guinée-Bissau',
      es: 'Guinea-Bisáu',
      pt: 'Guiné-Bissau',
      de: 'Guinea-Bissau',
    },
  },
  {
    code: 'GY',
    label: {
      en: 'Guyana',
      hi: 'गुयाना',
      fr: 'Guyana',
      es: 'Guyana',
      pt: 'Guiana',
      de: 'Guyana',
    },
  },
  {
    code: 'HT',
    label: {
      en: 'Haiti',
      hi: 'हैती',
      fr: 'Haïti',
      es: 'Haití',
      pt: 'Haiti',
      de: 'Haiti',
    },
  },
  {
    code: 'HM',
    label: {
      en: 'Heard Island & Mcdonald Islands',
      hi: 'हियर्ड द्वीप और मैकडोनाल्ड द्वीप',
      fr: 'Îles Heard-et-MacDonald',
      es: 'Islas Heard y McDonald',
      pt: 'Ilha Heard e Ilhas McDonald',
      de: 'Heard und McDonaldinseln',
    },
  },
  {
    code: 'VA',
    label: {
      en: 'Holy See (Vatican City State)',
      hi: 'होली सी (वेटिकन सिटी राज्य)',
      fr: 'Saint-Siège (État de la Cité du Vatican)',
      es: 'Vaticano, Ciudad del',
      pt: 'Vaticano',
      de: 'Vatikanstadt',
    },
  },
  {
    code: 'HN',
    label: {
      en: 'Honduras',
      hi: 'होंडुरास',
      fr: 'Honduras',
      es: 'Honduras',
      pt: 'Honduras',
      de: 'Honduras',
    },
  },
  {
    code: 'HK',
    label: {
      en: 'Hong Kong',
      hi: 'हांगकांग',
      fr: 'Hong Kong',
      es: 'Hong Kong',
      pt: 'Hong Kong',
      de: 'Hongkong',
    },
  },
  {
    code: 'HU',
    label: {
      en: 'Hungary',
      hi: 'हंगरी',
      fr: 'Hongrie',
      es: 'Hungría',
      pt: 'Hungria',
      de: 'Ungarn',
    },
  },
  {
    code: 'IS',
    label: {
      en: 'Iceland',
      hi: 'आइसलैंड',
      fr: 'Islande',
      es: 'Islandia',
      pt: 'Islândia',
      de: 'Island',
    },
  },
  {
    code: 'IN',
    label: {
      en: 'India',
      hi: 'भारत',
      fr: 'Inde',
      es: 'India',
      pt: 'Índia',
      de: 'Indien',
    },
  },
  {
    code: 'ID',
    label: {
      en: 'Indonesia',
      hi: 'इंडोनेशिया',
      fr: 'Indonésie',
      es: 'Indonesia',
      pt: 'Indonésia',
      de: 'Indonesien',
    },
  },
  {
    code: 'IR',
    label: {
      en: 'Iran}, Islamic Republic Of',
      hi: 'ईरान, इस्लामिक रिपब्लिक ऑफ',
      fr: 'Iran',
      es: 'Irán',
      pt: 'Irã',
      de: 'Iran',
    },
  },
  {
    code: 'IQ',
    label: {
      en: 'Iraq',
      hi: 'इराक',
      fr: 'Irak',
      es: 'Irak',
      pt: 'Iraque',
      de: 'Irak',
    },
  },
  {
    code: 'IE',
    label: {
      en: 'Ireland',
      hi: 'आयरलैंड',
      fr: 'Irlande',
      es: 'Irlanda',
      pt: 'Irlanda',
      de: 'Irland',
    },
  },
  {
    code: 'IM',
    label: {
      en: 'Isle Of Man',
      hi: 'आइल ऑफ मैन',
      fr: 'Île de Man',
      es: 'Isla de Man',
      pt: 'Ilha de Man',
      de: 'Insel Man',
    },
  },
  {
    code: 'IL',
    label: {
      en: 'Israel',
      hi: 'इज़राइल',
      fr: 'Israël',
      es: 'Israel',
      pt: 'Israel',
      de: 'Israel',
    },
  },
  {
    code: 'IT',
    label: {
      en: 'Italy',
      hi: 'इटली',
      fr: 'Italie',
      es: 'Italia',
      pt: 'Itália',
      de: 'Italien',
    },
  },
  {
    code: 'JM',
    label: {
      en: 'Jamaica',
      hi: 'जमैका',
      fr: 'Jamaïque',
      es: 'Jamaica',
      pt: 'Jamaica',
      de: 'Jamaika',
    },
  },
  {
    code: 'JP',
    label: {
      en: 'Japan',
      hi: 'जापान',
      fr: 'Japon',
      es: 'Japón',
      pt: 'Japão',
      de: 'Japan',
    },
  },
  {
    code: 'JE',
    label: {
      en: 'Jersey',
      hi: 'जर्सी',
      fr: 'Jersey',
      es: 'Jersey',
      pt: 'Jersey',
      de: 'Jersey (Kanalinsel)',
    },
  },
  {
    code: 'JO',
    label: {
      en: 'Jordan',
      hi: 'जॉर्डन',
      fr: 'Jordanie',
      es: 'Jordania',
      pt: 'Jordânia',
      de: 'Jordanien',
    },
  },
  {
    code: 'KZ',
    label: {
      en: 'Kazakhstan',
      hi: 'कज़ाकिस्तान',
      fr: 'Kazakhstan',
      es: 'Kazajistán',
      pt: 'Cazaquistão',
      de: 'Kasachstan',
    },
  },
  {
    code: 'KE',
    label: {
      en: 'Kenya',
      hi: 'केन्या',
      fr: 'Kenya',
      es: 'Kenia',
      pt: 'Quênia',
      de: 'Kenia',
    },
  },
  {
    code: 'KI',
    label: {
      en: 'Kiribati',
      hi: 'किरिबाती',
      fr: 'Kiribati',
      es: 'Kiribati',
      pt: 'Quiribáti',
      de: 'Kiribati',
    },
  },
  {
    code: 'KR',
    label: {
      en: 'Korea (Republic of)',
      hi: 'कोरिया (गणराज्य)',
      fr: 'Corée du Sud',
      es: 'Corea del Sur',
      pt: 'Coreia do Sul',
      de: 'Korea, Süd (Südkorea)',
    },
  },
  {
    code: 'KP',
    label: {
      en: "Korea (Democratic People's Republic of)",
      hi: 'कोरिया (लोकतांत्रिक जनवादी गणराज्य)',
      fr: 'Corée du Nord',
      es: 'Corea del Norte',
      pt: 'Coreia do Norte',
      de: 'Korea, Nord (Nordkorea)',
    },
  },
  {
    code: 'KW',
    label: {
      en: 'Kuwait',
      hi: 'कुवैत',
      fr: 'Koweït',
      es: 'Kuwait',
      pt: 'Kuwait',
      de: 'Kuwait',
    },
  },
  {
    code: 'KG',
    label: {
      en: 'Kyrgyzstan',
      hi: 'किर्गिज़स्तान',
      fr: 'Kirghizistan',
      es: 'Kirguistán',
      pt: 'Quirguistão',
      de: 'Kirgisistan',
    },
  },
  {
    code: 'LA',
    label: {
      en: "Lao People's Democratic Republic",
      hi: 'लाओ पीपुल्स डेमोक्रेटिक रिपब्लिक',
      fr: 'Laos',
      es: 'Laos',
      pt: 'Laos',
      de: 'Laos',
    },
  },
  {
    code: 'LV',
    label: {
      en: 'Latvia',
      hi: 'लातविया',
      fr: 'Lettonie',
      es: 'Letonia',
      pt: 'Letônia',
      de: 'Lettland',
    },
  },
  {
    code: 'LB',
    label: {
      en: 'Lebanon',
      hi: 'लेबनान',
      fr: 'Liban',
      es: 'Líbano',
      pt: 'Líbano',
      de: 'Libanon',
    },
  },
  {
    code: 'LS',
    label: {
      en: 'Lesotho',
      hi: 'लेसोथो',
      fr: 'Lesotho',
      es: 'Lesoto',
      pt: 'Lesoto',
      de: 'Lesotho',
    },
  },
  {
    code: 'LR',
    label: {
      en: 'Liberia',
      hi: 'लाइबेरिया',
      fr: 'Liberia',
      es: 'Liberia',
      pt: 'Libéria',
      de: 'Liberia',
    },
  },
  {
    code: 'LY',
    label: {
      en: 'Libyan Arab Jamahiriya',
      hi: 'लीबिया अरब जमाहिरिया',
      fr: 'Libye',
      es: 'Libia',
      pt: 'Líbia',
      de: 'Libyen',
    },
  },
  {
    code: 'LI',
    label: {
      en: 'Liechtenstein',
      hi: 'लिकटेंस्टीन',
      fr: 'Liechtenstein',
      es: 'Liechtenstein',
      pt: 'Listenstaine',
      de: 'Liechtenstein',
    },
  },
  {
    code: 'LT',
    label: {
      en: 'Lithuania',
      hi: 'लिथुआनिया',
      fr: 'Lituanie',
      es: 'Lituania',
      pt: 'Lituânia',
      de: 'Litauen',
    },
  },
  {
    code: 'LU',
    label: {
      en: 'Luxembourg',
      hi: 'लक्समबर्ग',
      fr: 'Luxembourg',
      es: 'Luxemburgo',
      pt: 'Luxemburgo',
      de: 'Luxemburg',
    },
  },
  {
    code: 'MO',
    label: {
      en: 'Macao',
      hi: 'मакаो',
      fr: 'Macao',
      es: 'Macao',
      pt: 'Macau',
      de: 'Macau',
    },
  },
  {
    code: 'MK',
    label: {
      en: 'Macedonia',
      hi: 'मैसेडोनिया',
      fr: 'Macédoine du Nord',
      es: 'Macedonia del Norte',
      pt: 'Macedônia do Norte',
      de: 'Nordmazedonien',
    },
  },
  {
    code: 'MG',
    label: {
      en: 'Madagascar',
      hi: 'मेडागास्कर',
      fr: 'Madagascar',
      es: 'Madagascar',
      pt: 'Madagáscar',
      de: 'Madagaskar',
    },
  },
  {
    code: 'MW',
    label: {
      en: 'Malawi',
      hi: 'मलावी',
      fr: 'Malawi',
      es: 'Malaui',
      pt: 'Maláui',
      de: 'Malawi',
    },
  },
  {
    code: 'MY',
    label: {
      en: 'Malaysia',
      hi: 'मलेशिया',
      fr: 'Malaisie',
      es: 'Malasia',
      pt: 'Malásia',
      de: 'Malaysia',
    },
  },
  {
    code: 'MV',
    label: {
      en: 'Maldives',
      hi: 'मालदीव',
      fr: 'Maldives',
      es: 'Maldivas',
      pt: 'Maldivas',
      de: 'Malediven',
    },
  },
  {
    code: 'ML',
    label: {
      en: 'Mali',
      hi: 'माली',
      fr: 'Mali',
      es: 'Malí',
      pt: 'Mali',
      de: 'Mali',
    },
  },
  {
    code: 'MT',
    label: {
      en: 'Malta',
      hi: 'माल्टा',
      fr: 'Malte',
      es: 'Malta',
      pt: 'Malta',
      de: 'Malta',
    },
  },
  {
    code: 'MH',
    label: {
      en: 'Marshall Islands',
      hi: 'मार्शल द्वीप',
      fr: 'Îles Marshall',
      es: 'Islas Marshall',
      pt: 'Ilhas Marshall',
      de: 'Marshallinseln',
    },
  },
  {
    code: 'MQ',
    label: {
      en: 'Martinique',
      hi: 'मार्टिनिक',
      fr: 'Martinique',
      es: 'Martinica',
      pt: 'Martinica',
      de: 'Martinique',
    },
  },
  {
    code: 'MR',
    label: {
      en: 'Mauritania',
      hi: 'मॉरिटानिया',
      fr: 'Mauritanie',
      es: 'Mauritania',
      pt: 'Mauritânia',
      de: 'Mauretanien',
    },
  },
  {
    code: 'MU',
    label: {
      en: 'Mauritius',
      hi: 'मॉरीशस',
      fr: 'Maurice',
      es: 'Mauricio',
      pt: 'Ilhas Maurícias',
      de: 'Mauritius',
    },
  },
  {
    code: 'YT',
    label: {
      en: 'Mayotte',
      hi: 'मायोट',
      fr: 'Mayotte',
      es: 'Mayotte',
      pt: 'Maiote',
      de: 'Mayotte',
    },
  },
  {
    code: 'MX',
    label: {
      en: 'Mexico',
      hi: 'मेक्सिको',
      fr: 'Mexique',
      es: 'México',
      pt: 'México',
      de: 'Mexiko',
    },
  },
  {
    code: 'FM',
    label: {
      en: 'Micronesia}, Federated States Of',
      hi: 'माइक्रोनेशिया, संघीय राज्य',
      fr: 'États fédérés de Micronésie',
      es: 'Micronesia',
      pt: 'Estados Federados da Micronésia',
      de: 'Mikronesien',
    },
  },
  {
    code: 'MD',
    label: {
      en: 'Moldova',
      hi: 'मोल्दोवा',
      fr: 'Moldavie',
      es: 'Moldavia',
      pt: 'Moldávia',
      de: 'Moldau',
    },
  },
  {
    code: ' MC',
    label: {
      en: 'Monaco',
      hi: 'मोनाको',
      fr: 'Monaco',
      es: 'Mónaco',
      pt: 'Mónaco',
      de: 'Monaco',
    },
  },
  {
    code: 'MN',
    label: {
      en: 'Mongolia',
      hi: 'मंगोलिया',
      fr: 'Mongolie',
      es: 'Mongolia',
      pt: 'Mongólia',
      de: 'Mongolei',
    },
  },
  {
    code: 'ME',
    label: {
      en: 'Montenegro',
      hi: 'मोंटेनेग्रो',
      fr: 'Monténégro',
      es: 'Montenegro',
      pt: 'Montenegro',
      de: 'Montenegro',
    },
  },
  {
    code: 'MS',
    label: {
      en: 'Montserrat',
      hi: 'मोंटसेराट',
      fr: 'Montserrat',
      es: 'Montserrat',
      pt: 'Monserrate',
      de: 'Montserrat',
    },
  },
  {
    code: 'MA',
    label: {
      en: 'Morocco',
      hi: 'मोरक्को',
      fr: 'Maroc',
      es: 'Marruecos',
      pt: 'Marrocos',
      de: 'Marokko',
    },
  },
  {
    code: 'MZ',
    label: {
      en: 'Mozambique',
      hi: 'मोज़ाम्बिक',
      fr: 'Mozambique',
      es: 'Mozambique',
      pt: 'Moçambique',
      de: 'Mosambik',
    },
  },
  {
    code: 'MM',
    label: {
      en: 'Myanmar',
      hi: 'म्यांमार',
      fr: 'Birmanie',
      es: 'Birmania',
      pt: 'Mianmar',
      de: 'Myanmar',
    },
  },
  {
    code: 'NA',
    label: {
      en: 'Namibia',
      hi: 'नामीबिया',
      fr: 'Namibie',
      es: 'Namibia',
      pt: 'Namíbia',
      de: 'Namibia',
    },
  },
  {
    code: 'NR',
    label: {
      en: 'Nauru',
      hi: 'नाउरू',
      fr: 'Nauru',
      es: 'Nauru',
      pt: 'Nauru',
      de: 'Nauru',
    },
  },
  {
    code: 'NP',
    label: {
      en: 'Nepal',
      hi: 'नेपाल',
      fr: 'Népal',
      es: 'Nepal',
      pt: 'Nepal',
      de: 'Nepal',
    },
  },
  {
    code: 'NL',
    label: {
      en: 'Netherlands',
      hi: 'नीदरलैंड',
      fr: 'Pays-Bas',
      es: 'Países Bajos',
      pt: 'Países Baixos',
      de: 'Niederlande',
    },
  },
  {
    code: 'NC',
    label: {
      en: 'New Caledonia',
      hi: 'न्यू कैलेडोनिया',
      fr: 'Nouvelle-Calédonie',
      es: 'Nueva Caledonia',
      pt: 'Nova Caledônia',
      de: 'Neukaledonien',
    },
  },
  {
    code: 'NZ',
    label: {
      en: 'New Zealand',
      hi: 'न्यूजीलैंड',
      fr: 'Nouvelle-Zélande',
      es: 'Nueva Zelanda',
      pt: 'Nova Zelândia',
      de: 'Neuseeland',
    },
  },
  {
    code: 'NI',
    label: {
      en: 'Nicaragua',
      hi: 'निकारागुआ',
      fr: 'Nicaragua',
      es: 'Nicaragua',
      pt: 'Nicarágua',
      de: 'Nicaragua',
    },
  },
  {
    code: 'NE',
    label: {
      en: 'Niger',
      hi: 'नाइजर',
      fr: 'Niger',
      es: 'Níger',
      pt: 'Níger',
      de: 'Niger',
    },
  },
  {
    code: 'NG',
    label: {
      en: 'Nigeria',
      hi: 'नाइजीरिया',
      fr: ' Nigeria',
      es: 'Nigeria',
      pt: 'Nigéria',
      de: 'Nigeria',
    },
  },
  {
    code: 'NU',
    label: {
      en: 'Niue',
      hi: 'न्यू',
      fr: 'Niue',
      es: 'Niue',
      pt: 'Niue',
      de: 'Niue',
    },
  },
  {
    code: 'NF',
    label: {
      en: 'Norfolk Island',
      hi: 'नॉरफ़ॉक द्वीप',
      fr: 'Île Norfolk',
      es: 'Isla Norfolk',
      pt: 'Ilha Norfolk',
      de: 'Norfolkinsel',
    },
  },
  {
    code: 'MP',
    label: {
      en: 'Northern Mariana Islands',
      hi: 'उत्तरी मारियाना द्वीप',
      fr: 'Îles Mariannes du Nord',
      es: 'Islas Marianas del Norte',
      pt: 'Marianas Setentrionais',
      de: 'Nördliche Marianen',
    },
  },
  {
    code: 'NO',
    label: {
      en: 'Norway',
      hi: 'नॉर्वे',
      fr: 'Norvège',
      es: 'Noruega',
      pt: 'Noruega',
      de: 'Norwegen',
    },
  },
  {
    code: 'OM',
    label: {
      en: 'Oman',
      hi: 'ओमान',
      fr: 'Oman',
      es: 'Omán',
      pt: 'Omã',
      de: 'Oman',
    },
  },
  {
    code: 'PK',
    label: {
      en: 'Pakistan',
      hi: 'पाकिस्तान',
      fr: 'Pakistan',
      es: 'Pakistán',
      pt: 'Paquistão',
      de: 'Pakistan',
    },
  },
  {
    code: 'PW',
    label: {
      en: 'Palau',
      hi: 'पलाऊ',
      fr: 'Palaos',
      es: 'Palaos',
      pt: 'Palau',
      de: 'Palau',
    },
  },
  {
    code: 'PS',
    label: {
      en: 'Palestinian Territory}, Occupied',
      hi: 'फिलिस्तीनी क्षेत्र, कब्जे वाला',
      fr: 'Palestine',
      es: 'Palestina',
      pt: 'Palestina',
      de: 'Palästina',
    },
  },
  {
    code: 'PA',
    label: {
      en: 'Panama',
      hi: 'पनामा',
      fr: 'Panama',
      es: 'Panamá',
      pt: 'Panamá',
      de: 'Panama',
    },
  },
  {
    code: 'PG',
    label: {
      en: 'Papua New Guinea',
      hi: 'पापुआ न्यू गिनी',
      fr: 'Papouasie-Nouvelle-Guinée',
      es: 'Papúa Nueva Guinea',
      pt: 'Papua-Nova Guiné',
      de: 'Papua-Neuguinea',
    },
  },
  {
    code: 'PY',
    label: {
      en: 'Paraguay',
      hi: 'पैराग्वे',
      fr: 'Paraguay',
      es: 'Paraguay',
      pt: 'Paraguai',
      de: 'Paraguay',
    },
  },
  {
    code: 'PE',
    label: {
      en: 'Peru',
      hi: 'पेरू',
      fr: 'Pérou',
      es: 'Perú',
      pt: 'Peru',
      de: 'Peru',
    },
  },
  {
    code: 'PH',
    label: {
      en: 'Philippines',
      hi: 'फिलीपींस',
      fr: 'Philippines',
      es: 'Filipinas',
      pt: 'Filipinas',
      de: 'Philippinen',
    },
  },
  {
    code: 'PN',
    label: {
      en: 'Pitcairn',
      hi: 'पिटकेर्न',
      fr: 'Îles Pitcairn',
      es: 'Islas Pitcairn',
      pt: 'Pitcairn',
      de: 'Pitcairninseln',
    },
  },
  {
    code: 'PL',
    label: {
      en: 'Poland',
      hi: 'पोलैंड',
      fr: 'Pologne',
      es: 'Polonia',
      pt: 'Polónia',
      de: 'Polen',
    },
  },
  {
    code: 'PT',
    label: {
      en: 'Portugal',
      hi: 'पुर्तगाल',
      fr: 'Portugal',
      es: 'Portugal',
      pt: 'Portugal',
      de: 'Portugal',
    },
  },
  {
    code: 'PR',
    label: {
      en: 'Puerto Rico',
      hi: 'प्यूर्टो रिको',
      fr: 'Porto Rico',
      es: 'Puerto Rico',
      pt: 'Porto Rico',
      de: 'Puerto Rico',
    },
  },
  {
    code: 'QA',
    label: {
      en: 'Qatar',
      hi: 'कतर',
      fr: 'Qatar',
      es: 'Catar',
      pt: 'Catar',
      de: 'Katar',
    },
  },
  {
    code: 'RE',
    label: {
      en: 'Reunion',
      hi: 'रीयूनियन',
      fr: 'La Réunion',
      es: 'Reunión',
      pt: 'Reunião',
      de: 'Réunion',
    },
  },
  {
    code: 'RO',
    label: {
      en: 'Romania',
      hi: 'रोमानिया',
      fr: 'Roumanie',
      es: 'Rumania',
      pt: 'Roménia',
      de: 'Rumänien',
    },
  },
  {
    code: 'RU',
    label: {
      en: 'Russian Federation',
      hi: 'रूसी संघ',
      fr: 'Russie',
      es: 'Rusia',
      pt: 'Rússia',
      de: 'Russland',
    },
  },
  {
    code: 'RW',
    label: {
      en: 'Rwanda',
      hi: 'रवांडा',
      fr: 'Rwanda',
      es: 'Ruanda',
      pt: 'Ruanda',
      de: 'Ruanda',
    },
  },
  {
    code: 'BL',
    label: {
      en: 'Saint Barthelemy',
      hi: 'सेंट बार्थेलेमी',
      fr: 'Saint-Barthélemy',
      es: 'San Bartolomé',
      pt: 'São Bartolomeu',
      de: 'Saint-Barthélemy',
    },
  },
  {
    code: 'SH',
    label: {
      en: 'Saint Helena',
      hi: 'सेंट हेलेना',
      fr: 'Sainte-Hélène, Ascension et Tristan da Cunha',
      es: 'Santa Elena, Ascensión y Tristán de Acuña',
      pt: 'Santa Helena, Ascensão e Tristão da Cunha',
      de: 'St. Helena, Ascension und Tristan da Cunha',
    },
  },
  {
    code: 'KN',
    label: {
      en: 'Saint Kitts And Nevis',
      hi: 'सेंट किट्स और नेविस',
      fr: 'Saint-Christophe-et-Niévès',
      es: 'San Cristóbal y Nieves',
      pt: 'São Cristóvão e Neves',
      de: 'St. Kitts und Nevis',
    },
  },
  {
    code: 'LC',
    label: {
      en: 'Saint Lucia',
      hi: 'सेंट लूसिया',
      fr: 'Sainte-Lucie',
      es: 'Santa Lucía',
      pt: 'Santa Lúcia',
      de: 'St. Lucia',
    },
  },
  {
    code: 'MF',
    label: {
      en: 'Saint Martin (France)',
      hi: 'सेंट मार्टिन (फ्रांस)',
      fr: 'Saint-Martin (France)',
      es: 'San Martín (Francia)',
      pt: 'São Martinho (França)',
      de: 'Saint-Martin (französischer Teil)',
    },
  },
  {
    code: 'SX',
    label: {
      en: 'Saint Martin',
      hi: 'सेंट मार्टिन',
      fr: 'Saint-Martin',
      es: 'San Martín',
      pt: 'São Martinho',
      de: 'Sint Maarten',
    },
  },
  {
    code: 'PM',
    label: {
      en: 'Saint Pierre And Miquelon',
      hi: 'सेंट पियरे और मिकेलॉन',
      fr: 'Saint-Pierre-et-Miquelon',
      es: 'San Pedro y Miquelón',
      pt: 'São Pedro e Miquelão',
      de: 'Saint-Pierre und Miquelon',
    },
  },
  {
    code: 'VC',
    label: {
      en: 'Saint Vincent And Grenadines',
      hi: 'सेंट विंसेंट और ग्रेनेडाइंस',
      fr: 'Saint-Vincent-et-les-Grenadines',
      es: 'San Vicente y las Granadinas',
      pt: 'São Vicente e Granadinas',
      de: 'St. Vincent und die Grenadinen',
    },
  },
  {
    code: 'WS',
    label: {
      en: 'Samoa',
      hi: 'समोआ',
      fr: 'Samoa',
      es: 'Samoa',
      pt: 'Samoa',
      de: 'Samoa',
    },
  },
  {
    code: 'SM',
    label: {
      en: 'San Marino',
      hi: 'सैन मैरिनो',
      fr: 'Saint-Marin',
      es: 'San Marino',
      pt: 'San Marino',
      de: 'San Marino',
    },
  },
  {
    code: 'ST',
    label: {
      en: 'Sao Tome And Principe',
      hi: 'साओ टोमे और प्रिंसिपे',
      fr: 'Sao Tomé-et-Principe',
      es: 'Santo Tomé y Príncipe',
      pt: 'São Tomé e Príncipe',
      de: 'São Tomé und Príncipe',
    },
  },
  {
    code: 'SA',
    label: {
      en: 'Saudi Arabia',
      hi: 'सऊदी अरब',
      fr: 'Arabie saoudite',
      es: 'Arabia Saudita',
      pt: 'Arábia Saudita',
      de: 'Saudi-Arabien',
    },
  },
  {
    code: 'SN',
    label: {
      en: 'Senegal',
      hi: 'सेनेगल',
      fr: 'Sénégal',
      es: 'Senegal',
      pt: 'Senegal',
      de: 'Senegal',
    },
  },
  {
    code: 'RS',
    label: {
      en: 'Serbia',
      hi: 'सर्बिया',
      fr: 'Serbie',
      es: 'Serbia',
      pt: 'Sérvia',
      de: 'Serbien',
    },
  },
  {
    code: 'SC',
    label: {
      en: 'Seychelles',
      hi: 'सेशेल्स',
      fr: 'Seychelles',
      es: 'Seychelles',
      pt: 'Seicheles',
      de: 'Seychellen',
    },
  },
  {
    code: 'SL',
    label: {
      en: 'Sierra Leone',
      hi: 'सिएरा लियोन',
      fr: 'Sierra Leone',
      es: 'Sierra Leona',
      pt: 'Serra Leoa',
      de: 'Sierra Leone',
    },
  },
  {
    code: 'SG',
    label: {
      en: 'Singapore',
      hi: 'सिंगापुर',
      fr: 'Singapour',
      es: 'Singapur',
      pt: 'Singapura',
      de: 'Singapur',
    },
  },
  {
    code: 'SK',
    label: {
      en: 'Slovakia',
      hi: 'स्लोवाकिया',
      fr: 'Slovaquie',
      es: 'Eslovaquia',
      pt: 'Eslováquia',
      de: 'Slowakei',
    },
  },
  {
    code: 'SI',
    label: {
      en: 'Slovenia',
      hi: 'स्लोवेनिया',
      fr: 'Slovénie',
      es: 'Eslovenia',
      pt: 'Eslovênia',
      de: 'Slowenien',
    },
  },
  {
    code: 'SB',
    label: {
      en: 'Solomon Islands',
      hi: 'सोलोमन द्वीप',
      fr: 'Îles Salomon',
      es: 'Islas Salomón',
      pt: 'Ilhas Salomão',
      de: 'Sal omonen',
    },
  },
  {
    code: 'SO',
    label: {
      en: 'Somalia',
      hi: 'सोमालिया',
      fr: 'Somalie',
      es: 'Somalia',
      pt: 'Somália',
      de: 'Somalia',
    },
  },
  {
    code: 'ZA',
    label: {
      en: 'South Africa',
      hi: 'दक्षिण अफ़्रीका',
      fr: 'Afrique du Sud',
      es: 'Sudáfrica',
      pt: 'África do Sul',
      de: 'Südafrika',
    },
  },
  {
    code: 'GS',
    label: {
      en: 'South Georgia And Sandwich Isl.',
      hi: 'दक्षिण जॉर्जिया और सैंडविच द्वीप',
      fr: 'Géorgie du Sud-et-les îles Sandwich du Sud',
      es: 'Islas Georgias del Sur y Sandwich del Sur',
      pt: 'Ilhas Geórgia do Sul e Sandwich do Sul',
      de: 'Südgeorgien und die Südlichen Sandwichinseln',
    },
  },
  {
    code: 'SS',
    label: {
      en: 'South Sudan',
      hi: 'दक्षिण सूडान',
      fr: 'Soudan du Sud',
      es: 'Sudán del Sur',
      pt: 'Sudão do Sul',
      de: 'Südsudan',
    },
  },
  {
    code: 'ES',
    label: {
      en: 'Spain',
      hi: 'स्पेन',
      fr: 'Espagne',
      es: 'España',
      pt: 'Espanha',
      de: 'Spanien',
    },
  },
  {
    code: 'LK',
    label: {
      en: 'Sri Lanka',
      hi: 'श्रीलंका',
      fr: 'Sri Lanka',
      es: 'Sri Lanka',
      pt: 'Seri Lanca',
      de: 'Sri Lanka',
    },
  },
  {
    code: 'SD',
    label: {
      en: 'Sudan',
      hi: 'सूडान',
      fr: 'Soudan',
      es: 'Sudán',
      pt: 'Sudão',
      de: 'Sudan',
    },
  },
  {
    code: 'SR',
    label: {
      en: 'Suriname',
      hi: 'सूरीनाम',
      fr: 'Suriname',
      es: 'Surinam',
      pt: 'Suriname',
      de: 'Suriname',
    },
  },
  {
    code: 'SJ',
    label: {
      en: 'Svalbard And Jan Mayen',
      hi: 'स्वालबार्ड और जान मायेन',
      fr: 'Svalbard et île Jan Mayen',
      es: 'Svalbard y Jan Mayen',
      pt: 'Esvalbarde e Jan Mayen',
      de: 'Spitzbergen und Jan Mayen',
    },
  },
  {
    code: 'SZ',
    label: {
      en: 'Swaziland',
      hi: 'स्वाज़ीलैंड',
      fr: 'Eswatini',
      es: 'Suazilandia',
      pt: 'Essuatíni',
      de: 'Eswatini',
    },
  },
  {
    code: 'SE',
    label: {
      en: 'Sweden',
      hi: 'स्वीडन',
      fr: 'Suède',
      es: 'Suecia',
      pt: 'Suécia',
      de: 'Schweden',
    },
  },
  {
    code: 'CH',
    label: {
      en: 'Switzerland',
      hi: 'स्विट्ज़रलैंड',
      fr: 'Suisse',
      es: 'Suiza',
      pt: 'Suíça',
      de: 'Schweiz',
    },
  },
  {
    code: 'SY',
    label: {
      en: 'Syrian Arab Republic',
      hi: 'सीरियाई अरब गणराज्य',
      fr: 'Syrie',
      es: 'Siria',
      pt: 'Síria',
      de: 'Syrien',
    },
  },
  {
    code: 'TW',
    label: {
      en: 'Taiwan',
      hi: 'ताइवान',
      fr: 'Taïwan (République de Chine)',
      es: 'Taiwán (República de China)',
      pt: 'Taiwan',
      de: 'China, Republik ',
    },
  },
  {
    code: 'TJ',
    label: {
      en: 'Tajikistan',
      hi: 'ताजिकिस्तान',
      fr: 'Tadjikistan',
      es: 'Tayikistán',
      pt: 'Tajiquistão',
      de: 'Tadschikistan',
    },
  },
  {
    code: 'TZ',
    label: {
      en: 'Tanzania',
      hi: 'तंजानिया',
      fr: 'Tanzanie',
      es: 'Tanzania',
      pt: 'Tanzânia',
      de: 'Tansania',
    },
  },
  {
    code: 'TH',
    label: {
      en: 'Thailand',
      hi: 'थाईलैंड',
      fr: 'Thaïlande',
      es: 'Tailandia',
      pt: 'Tailândia',
      de: 'Thailand',
    },
  },
  {
    code: 'TL',
    label: {
      en: 'Timor-Leste',
      hi: 'तिमोर-लेस्ते',
      fr: 'Timor oriental',
      es: 'Timor Oriental',
      pt: 'Timor-Leste',
      de: 'Osttimor',
    },
  },
  {
    code: 'TG',
    label: {
      en: 'Togo',
      hi: 'टोगो',
      fr: 'Togo',
      es: 'Togo',
      pt: 'Togo',
      de: 'Togo',
    },
  },
  {
    code: 'TK',
    label: {
      en: 'Tokelau',
      hi: 'टोकेलाऊ',
      fr: 'Tokelau',
      es: 'Tokelau',
      pt: 'Toquelau',
      de: 'Tokelau',
    },
  },
  {
    code: 'TO',
    label: {
      en: 'Tonga',
      hi: 'टोंगा',
      fr: 'Tonga',
      es: 'Tonga',
      pt: 'Tonga',
      de: 'Tonga',
    },
  },
  {
    code: 'TT',
    label: {
      en: 'Trinidad And Tobago',
      hi: 'त्रिनिदाद और टोबैगो',
      fr: 'Trinité-et-Tobago',
      es: 'Trinidad y Tobago',
      pt: 'Trinidad e Tobago',
      de: 'Trinidad und Tobago',
    },
  },
  {
    code: 'TN',
    label: {
      en: 'Tunisia',
      hi: 'ट्यूनिशिया',
      fr: 'Tunisie',
      es: 'Túnez',
      pt: 'Tunísia',
      de: 'Tunesien',
    },
  },
  {
    code: 'TR',
    label: {
      en: 'Turkey',
      hi: 'तुर्की',
      fr: 'Turquie',
      es: 'Turquía',
      pt: 'Turquia',
      de: 'Türkei',
    },
  },
  {
    code: 'TM',
    label: {
      en: 'Turkmenistan',
      hi: 'तुर्कमेनिस्तान',
      fr: 'Turkménistan',
      es: 'Turkmenistán',
      pt: 'Turcomenistão',
      de: 'Turkmenistan',
    },
  },
  {
    code: 'TC',
    label: {
      en: 'Turks And Caicos Islands',
      hi: 'तुर्क और कैकोस द्वीप',
      fr: 'Îles Turques-et-Caïques',
      es: 'Islas Turcas y Caicos',
      pt: 'Turcas e Caicos',
      de: 'Turks- und Caicosinseln',
    },
  },
  {
    code: 'TV',
    label: {
      en: 'Tuvalu',
      hi: 'तुवालु',
      fr: 'Tuvalu',
      es: 'Tuvalu',
      pt: 'Tuvalu',
      de: 'Tuvalu',
    },
  },
  {
    code: 'UG',
    label: {
      en: 'Uganda',
      hi: 'युगांडा',
      fr: 'Ouganda',
      es: 'Uganda',
      pt: 'Uganda',
      de: 'Uganda',
    },
  },
  {
    code: 'UA',
    label: {
      en: 'Ukraine',
      hi: 'यूक्रेन',
      fr: 'Ukraine',
      es: 'Ucrania',
      pt: 'Ucrânia',
      de: 'Ukraine',
    },
  },
  {
    code: 'AE',
    label: {
      en: 'United Arab Emirates',
      hi: 'संयुक्त अरब अमीरात',
      fr: 'Émirats arabes unis',
      es: 'Emiratos Árabes Unidos',
      pt: 'Emirados Árabes Unidos',
      de: 'Vereinigte Arabische Emirate',
    },
  },
  {
    code: 'GB',
    label: {
      en: 'United Kingdom',
      hi: 'यूनाइटेड किंगडम',
      fr: 'Royaume-Uni',
      es: 'Reino Unido',
      pt: 'Reino Unido',
      de: 'Vereinigtes Königreich',
    },
  },
  {
    code: 'US',
    label: {
      en: 'United States',
      hi: 'संयुक्त राज्य अमेरिका',
      fr: 'États-Unis',
      es: 'Estados Unidos',
      pt: 'Estados Unidos',
      de: 'Vereinigte Staaten',
    },
  },
  {
    code: 'UM',
    label: {
      en: 'United States Outlying Islands',
      hi: 'संयुक्त राज्य अमेरिका के बाहरी द्वीप',
      fr: 'Îles mineures éloignées des États-Unis',
      es: 'Islas Ultramarinas Menores de los Estados Unidos',
      pt: 'Ilhas Menores Distantes dos Estados Unidos',
      de: 'United States Minor Outlying Islands',
    },
  },
  {
    code: 'UY',
    label: {
      en: 'Uruguay',
      hi: 'उरुग्वे',
      fr: 'Uruguay',
      es: 'Uruguay',
      pt: 'Uruguai',
      de: 'Uruguay',
    },
  },
  {
    code: 'UZ',
    label: {
      en: 'Uzbekistan',
      hi: 'उज़्बेकिस्तान',
      fr: 'Ouzbékistan',
      es: 'Uzbekistán',
      pt: 'Uzbequistão',
      de: 'Usbekistan',
    },
  },
  {
    code: 'VU',
    label: {
      en: 'Vanuatu',
      hi: 'वानूआतू',
      fr: 'Vanuatu',
      es: 'Vanuatu',
      pt: 'Vanuatu',
      de: 'Vanuatu',
    },
  },
  {
    code: 'VE',
    label: {
      en: 'Venezuela',
      hi: 'वेनेज़ुएला',
      fr: 'Venezuela',
      es: 'Venezuela',
      pt: 'Venezuela',
      de: 'Venezuela',
    },
  },
  {
    code: 'VN',
    label: {
      en: 'Vietnam',
      hi: 'वियतनाम',
      fr: 'Viêt Nam',
      es: 'Vietnam',
      pt: 'Vietname',
      de: 'Vietnam',
    },
  },
  {
    code: 'VG',
    label: {
      en: 'Virgin Islands}, British',
      hi: 'वर्जिन द्वीप, ब्रिटिश',
      fr: 'Îles Vierges britanniques',
      es: 'Islas Vírgenes Británicas',
      pt: 'Ilhas Virgens Britânicas',
      de: 'Britische Jungferninseln',
    },
  },
  {
    code: 'VI',
    label: {
      en: 'Virgin Islands}, U.S.',
      hi: 'वर्जिन द्वीप, यू.एस.',
      fr: 'Îles Vierges des États-Unis',
      es: 'Islas Vírgenes de los Estados Unidos',
      pt: 'Ilhas Virgens Americanas',
      de: 'Amerikanische Jungferninseln',
    },
  },
  {
    code: 'WF',
    label: {
      en: 'Wallis And Futuna',
      hi: 'वालिस और फ़्यूचूना',
      fr: 'Wallis-et-Futuna',
      es: 'Wallis y Futuna',
      pt: 'Wallis e Futuna',
      de: 'Wallis und Futuna',
    },
  },
  {
    code: 'EH',
    label: {
      en: 'Western Sahara',
      hi: 'पश्चिमी सहारा',
      fr: 'République arabe sahraouie démocratique',
      es: 'República Árabe Saharaui Democrática',
      pt: 'Saara Ocidental',
      de: 'Westsahara',
    },
  },
  {
    code: 'YE',
    label: {
      en: 'Yemen',
      hi: 'यमन',
      fr: 'Yémen',
      es: 'Yemen',
      pt: 'Iêmen',
      de: 'Jemen',
    },
  },
  {
    code: 'ZM',
    label: {
      en: 'Zambia',
      hi: 'ज़ाम्बिया',
      fr: 'Zambie',
      es: 'Zambia',
      pt: 'Zâmbia',
      de: 'Sambia',
    },
  },
  {
    code: 'ZW',
    label: {
      en: 'Zimbabwe',
      hi: 'ज़िम्बाब्वे',
      fr: 'Zimbabwe',
      es: 'Zimbabue',
      pt: 'Zimbábue',
      de: 'Simbabwe',
    },
  },
];
