export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const THERAPY_BOOKING_OPENED = 'THERAPY_BOOKING_OPENED';
export const THERAPY_CONFIRMATION_VIEWED = 'THERAPY_CONFIRMATION_VIEWED';
