# This file contains the configs for dependabot.
# See for more info:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # same value for yarn
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/London"
    assignees:
      - kyleecodes
    reviewers:
      - kyleecodes
    groups:
      dev-deps:
        dependency-type: "development"
        update-types: # Excludes major updates so we can review individually
          - "minor"
          - "patch"
      prod-deps:
        dependency-type: "production"
        update-types: # Excludes major updates so we can review individually
          - "minor"
          - "patch"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`.
    # (You don't need to specify `/.github/workflows` for `directory`.
    # You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/London"
    assignees:
      - kyleecodes
    reviewers:
      - kyleecodes
    groups:
      actions-deps:
        patterns:
          - "*" # Group all GitHub Actions updates together

