ci:
  collect:
    url: https://bloom-frontend-git-develop-chaynhq.vercel.app
    puppeteerScript: config/puppeteerLogin.js
    settings:
      emulatedFormFactor: desktop
      disableStorageReset: true
