ci:
  collect:
    url: https://bloom-frontend-git-develop-chaynhq.vercel.app
    disableStorageReset: true
    puppeteerScript: config/puppeteerLogin.js
    puppeteerLaunchOptions:
      args:
        - '--allow-no-sandbox-job'
        - '--allow-sandbox-debugging'
        - '--no-sandbox'
        - '--disable-gpu'
        - '--disable-gpu-sandbox'
        - '--display'

    settings:
      emulatedFormFactor: mobile
      disableStorageReset: true
