version: '0.1'
environments:
  - name: develop
    branch: develop
    mode: pull-request
apps:
  - name: bloom-frontend
    path: ''
    text-resources:
      - path: messages/*/*.json
        format: nested-key-value
