export default [
  {
    code: 'AF',
    label: {
      en: 'Afghanistan',
      hi: 'Afghanistan',
      fr: 'Afghanistan',
      es: 'Afganistán',
      pt: 'Afeganistão',
      de: 'Afghanistan',
    },
  },
  {
    code: 'AX',
    label: {
      en: 'Aland Islands',
      hi: 'Aland Islands',
      fr: 'Îles Åland',
      es: 'Åland',
      pt: 'Ilhas Åland',
      de: 'Åland',
    },
  },
  {
    code: 'AL',
    label: {
      en: 'Albania',
      hi: 'Albania',
      fr: 'Albanie',
      es: 'Albania',
      pt: 'Albânia',
      de: 'Albanien',
    },
  },
  {
    code: 'DZ',
    label: {
      en: 'Algeria',
      hi: 'Algeria',
      fr: 'Algérie',
      es: 'Argelia',
      pt: 'Argélia',
      de: 'Algerien',
    },
  },
  {
    code: 'AS',
    label: {
      en: 'American Samoa',
      hi: 'American Samoa',
      fr: 'Samoa américaines',
      es: 'Samoa Americana',
      pt: 'Samoa Americana',
      de: 'Amerikanisch-Samoa',
    },
  },
  {
    code: 'AD',
    label: {
      en: 'Andorra',
      hi: 'Andorra',
      fr: 'Andorre',
      es: 'Andorra',
      pt: 'Andorra',
      de: 'Andorra',
    },
  },
  {
    code: 'AO',
    label: { en: 'Angola', hi: 'Angola', fr: 'Angola', es: 'Angola', pt: 'Angola', de: 'Angola' },
  },
  {
    code: 'AI',
    label: {
      en: 'Anguilla',
      hi: 'Anguilla',
      fr: 'Anguilla',
      es: 'Anguila',
      pt: 'Anguila',
      de: 'Anguilla',
    },
  },
  {
    code: 'AQ',
    label: {
      en: 'Antarctica',
      hi: 'Antarctica',
      fr: 'Antarctique',
      es: 'Antártida',
      pt: 'Antártida',
      de: 'Antarktis (Sonderstatus durch Antarktisvertrag)',
    },
  },
  {
    code: 'AG',
    label: {
      en: 'Antigua And Barbuda',
      hi: 'Antigua And Barbuda',
      fr: 'Antigua-et-Barbuda',
      es: 'Antigua y Barbuda',
      pt: 'Antígua e Barbuda',
      de: 'Antigua und Barbuda',
    },
  },
  {
    code: 'AR',
    label: {
      en: 'Argentina',
      hi: 'Argentina',
      fr: 'Argentine',
      es: 'Argentina',
      pt: 'Argentina',
      de: 'Argentinien',
    },
  },
  {
    code: 'AM',
    label: {
      en: 'Armenia',
      hi: 'Armenia',
      fr: 'Arménie',
      es: 'Armenia',
      pt: 'Armênia',
      de: 'Armenien',
    },
  },
  {
    code: 'AW',
    label: { en: 'Aruba', hi: 'Aruba', fr: 'Aruba', es: 'Aruba', pt: 'Aruba', de: 'Aruba' },
  },
  {
    code: 'AU',
    label: {
      en: 'Australia',
      hi: 'Australia',
      fr: 'Australie',
      es: 'Australia',
      pt: 'Austrália',
      de: 'Australien',
    },
  },
  {
    code: 'AT',
    label: {
      en: 'Austria',
      hi: 'Austria',
      fr: 'Autriche',
      es: 'Austria',
      pt: 'Áustria',
      de: 'Österreich',
    },
  },
  {
    code: 'AZ',
    label: {
      en: 'Azerbaijan',
      hi: 'Azerbaijan',
      fr: 'Azerbaïdjan',
      es: 'Azerbaiyán',
      pt: 'Azerbaijão',
      de: 'Aserbaidschan',
    },
  },
  {
    code: 'BS',
    label: {
      en: 'Bahamas',
      hi: 'Bahamas',
      fr: 'Bahamas',
      es: 'Bahamas',
      pt: 'Bahamas',
      de: 'Bahamas',
    },
  },
  {
    code: 'BH',
    label: {
      en: 'Bahrain',
      hi: 'Bahrain',
      fr: 'Bahreïn',
      es: 'Baréin',
      pt: 'Barém',
      de: 'Bahrain',
    },
  },
  {
    code: 'BD',
    label: {
      en: 'Bangladesh',
      hi: 'Bangladesh',
      fr: 'Bangladesh',
      es: 'Bangladés',
      pt: 'Bangladexe',
      de: 'Bangladesch',
    },
  },
  {
    code: 'BB',
    label: {
      en: 'Barbados',
      hi: 'Barbados',
      fr: 'Barbade',
      es: 'Barbados',
      pt: 'Barbados',
      de: 'Barbados',
    },
  },
  {
    code: 'BY',
    label: {
      en: 'Belarus',
      hi: 'Belarus',
      fr: 'Biélorussie',
      es: 'Bielorrusia',
      pt: 'Bielorrússia',
      de: 'Belarus',
    },
  },
  {
    code: 'BE',
    label: {
      en: 'Belgium',
      hi: 'Belgium',
      fr: 'Belgique',
      es: 'Bélgica',
      pt: 'Bélgica',
      de: 'Belgien',
    },
  },
  {
    code: 'BZ',
    label: { en: 'Belize', hi: 'Belize', fr: 'Belize', es: 'Belice', pt: 'Belize', de: 'Belize' },
  },
  {
    code: 'BJ',
    label: { en: 'Benin', hi: 'Benin', fr: 'Bénin', es: 'Benín', pt: 'Benim', de: 'Benin' },
  },
  {
    code: 'BM',
    label: {
      en: 'Bermuda',
      hi: 'Bermuda',
      fr: 'Bermudes',
      es: 'Bermudas',
      pt: 'Bermudas',
      de: 'Bermuda',
    },
  },
  {
    code: 'BT',
    label: { en: 'Bhutan', hi: 'Bhutan', fr: 'Bhoutan', es: 'Bután', pt: 'Butão', de: 'Bhutan' },
  },
  {
    code: 'BO',
    label: {
      en: 'Bolivia',
      hi: 'Bolivia',
      fr: 'Bolivie',
      es: 'Bolivia',
      pt: 'Bolívia',
      de: 'Bolivien',
    },
  },
  {
    code: 'BQ',
    label: {
      en: 'Bonaire, Sint Eustatius and Saba',
      hi: 'Bonaire, Sint Eustatius and Saba',
      fr: 'Pays-Bas caribéens',
      es: 'Bonaire, San Eustaquio y Saba',
      pt: 'Países Baixos Caribenhos',
      de: 'Bonaire, Saba, Sint Eustatius',
    },
  },
  {
    code: 'BA',
    label: {
      en: 'Bosnia And Herzegovina',
      hi: 'Bosnia And Herzegovina',
      fr: 'Bosnie-Herzégovine',
      es: 'Bosnia y Herzegovina',
      pt: 'Bósnia e Herzegovina',
      de: 'Bosnien und Herzegowina',
    },
  },
  {
    code: 'BW',
    label: {
      en: 'Botswana',
      hi: 'Botswana',
      fr: 'Botswana',
      es: 'Botsuana',
      pt: 'Botsuana',
      de: 'Botswana',
    },
  },
  {
    code: 'BV',
    label: {
      en: 'Bouvet Island',
      hi: 'Bouvet Island',
      fr: 'Île Bouvet',
      es: 'Isla Bouvet',
      pt: 'Ilha Bouvet',
      de: 'Bouvetinsel',
    },
  },
  {
    code: 'BR',
    label: {
      en: 'Brazil',
      hi: 'Brazil',
      fr: 'Brésil',
      es: 'Brasil',
      pt: 'Brasil',
      de: 'Brasilien',
    },
  },
  {
    code: 'IO',
    label: {
      en: 'British Indian Ocean Territory',
      hi: 'British Indian Ocean Territory',
      fr: "Territoire britannique de l'océan Indien",
      es: 'Territorio Británico del Océano Índico',
      pt: 'Território Britânico do Oceano Índico',
      de: 'Britisches Territorium im Indischen Ozean',
    },
  },
  {
    code: 'BN',
    label: {
      en: 'Brunei Darussalam',
      hi: 'Brunei Darussalam',
      fr: 'Brunei',
      es: 'Brunéi',
      pt: 'Brunei',
      de: 'Brunei',
    },
  },
  {
    code: 'BG',
    label: {
      en: 'Bulgaria',
      hi: 'Bulgaria',
      fr: 'Bulgarie',
      es: 'Bulgaria',
      pt: 'Bulgária',
      de: 'Bulgarien',
    },
  },
  {
    code: 'BF',
    label: {
      en: 'Burkina Faso',
      hi: 'Burkina Faso',
      fr: 'Burkina Faso',
      es: 'Burkina Faso',
      pt: 'Burquina Fasso',
      de: 'Burkina Faso',
    },
  },
  {
    code: 'BI',
    label: {
      en: 'Burundi',
      hi: 'Burundi',
      fr: 'Burundi',
      es: 'Burundi',
      pt: 'Burundi',
      de: 'Burundi',
    },
  },
  {
    code: 'KH',
    label: {
      en: 'Cambodia',
      hi: 'Cambodia',
      fr: 'Cambodge',
      es: 'Camboya',
      pt: 'Camboja',
      de: 'Kambodscha',
    },
  },
  {
    code: 'CM',
    label: {
      en: 'Cameroon',
      hi: 'Cameroon',
      fr: 'Cameroun',
      es: 'Camerún',
      pt: 'Camarões',
      de: 'Kamerun',
    },
  },
  {
    code: 'CA',
    label: { en: 'Canada', hi: 'Canada', fr: 'Canada', es: 'Canadá', pt: 'Canadá', de: 'Kanada' },
  },
  {
    code: 'CV',
    label: {
      en: 'Cape Verde',
      hi: 'Cape Verde',
      fr: 'Cap-Vert',
      es: 'Cabo Verde',
      pt: 'Cabo Verde',
      de: 'Kap Verde',
    },
  },
  {
    code: 'KY',
    label: {
      en: 'Cayman Islands',
      hi: 'Cayman Islands',
      fr: 'Îles Caïmans',
      es: 'Islas Caimán',
      pt: 'Ilhas Caimã',
      de: 'Kaimaninseln',
    },
  },
  {
    code: 'CF',
    label: {
      en: 'Central African Republic',
      hi: 'Central African Republic',
      fr: 'République centrafricaine',
      es: 'República Centroafricana',
      pt: 'República Centro-Africana',
      de: 'Zentralafrikanische Republik',
    },
  },
  {
    code: 'TD',
    label: { en: 'Chad', hi: 'Chad', fr: 'Tchad', es: 'Chad', pt: 'Chade', de: 'Tschad' },
  },
  {
    code: 'CL',
    label: { en: 'Chile', hi: 'Chile', fr: 'Chili', es: 'Chile', pt: 'Chile', de: 'Chile' },
  },
  {
    code: 'CN',
    label: {
      en: 'China',
      hi: 'China',
      fr: 'Chine',
      es: 'China',
      pt: 'China',
      de: 'China, Volksrepublik',
    },
  },
  {
    code: 'CX',
    label: {
      en: 'Christmas Island',
      hi: 'Christmas Island',
      fr: 'Île Christmas',
      es: 'Isla de Navidad',
      pt: 'Ilha do Natal',
      de: 'Weihnachtsinsel',
    },
  },
  {
    code: 'CC',
    label: {
      en: 'Cocos (Keeling) Islands',
      hi: 'Cocos (Keeling) Islands',
      fr: 'Îles Cocos',
      es: 'Islas Cocos',
      pt: 'Ilhas Cocos (Keeling)',
      de: 'Kokosinseln',
    },
  },
  {
    code: 'CO',
    label: {
      en: 'Colombia',
      hi: 'Colombia',
      fr: 'Colombie',
      es: 'Colombia',
      pt: 'Colômbia',
      de: 'Kolumbien',
    },
  },
  {
    code: 'KM',
    label: {
      en: 'Comoros',
      hi: 'Comoros',
      fr: 'Comores',
      es: 'Comoras',
      pt: 'Comores',
      de: 'Komoren',
    },
  },
  {
    code: 'CG',
    label: {
      en: 'Congo',
      hi: 'Congo',
      fr: 'République du Congo',
      es: 'República del Congo',
      pt: 'República do Congo',
      de: 'Kongo, Republik',
    },
  },
  {
    code: 'CD',
    label: {
      en: 'Congo}, Democratic Republic',
      hi: 'Congo}, Democratic Republic',
      fr: 'République démocratique du Congo',
      es: 'República Democrática del Congo',
      pt: 'República Democrática do Congo',
      de: 'Kongo, Demokratische Republik',
    },
  },
  {
    code: 'CK',
    label: {
      en: 'Cook Islands',
      hi: 'Cook Islands',
      fr: 'Îles Cook',
      es: 'Islas Cook',
      pt: 'Ilhas Cook',
      de: 'Cookinseln',
    },
  },
  {
    code: 'CR',
    label: {
      en: 'Costa Rica',
      hi: 'Costa Rica',
      fr: 'Costa Rica',
      es: 'Costa Rica',
      pt: 'Costa Rica',
      de: 'Costa Rica',
    },
  },
  {
    code: 'CI',
    label: {
      en: "Cote D'Ivoire",
      hi: "Cote D'Ivoire",
      fr: "Côte d'Ivoire",
      es: 'Costa de Marfil',
      pt: 'Costa do Marfim',
      de: 'Elfenbeinküste',
    },
  },
  {
    code: 'HR',
    label: {
      en: 'Croatia',
      hi: 'Croatia',
      fr: 'Croatie',
      es: 'Croacia',
      pt: 'Croácia',
      de: 'Kroatien',
    },
  },
  { code: 'CU', label: { en: 'Cuba', hi: 'Cuba', fr: 'Cuba', es: 'Cuba', pt: 'Cuba', de: 'Kuba' } },
  {
    code: 'CY',
    label: { en: 'Cyprus', hi: 'Cyprus', fr: 'Chypre', es: 'Chipre', pt: 'Chipre', de: 'Zypern' },
  },
  {
    code: 'CZ',
    label: {
      en: 'Czech Republic',
      hi: 'Czech Republic',
      fr: 'Tchéquie',
      es: 'República Checa',
      pt: 'Chéquia',
      de: 'Tschechien',
    },
  },
  {
    code: 'DK',
    label: {
      en: 'Denmark',
      hi: 'Denmark',
      fr: 'Danemark',
      es: 'Dinamarca',
      pt: 'Dinamarca',
      de: 'Dänemark',
    },
  },
  {
    code: 'DJ',
    label: {
      en: 'Djibouti',
      hi: 'Djibouti',
      fr: 'Djibouti',
      es: 'Yibuti',
      pt: 'Djibuti',
      de: 'Dschibuti',
    },
  },
  {
    code: 'DM',
    label: {
      en: 'Dominica',
      hi: 'Dominica',
      fr: 'Dominique',
      es: 'Dominica',
      pt: 'Dominica',
      de: 'Dominica',
    },
  },
  {
    code: 'DO',
    label: {
      en: 'Dominican Republic',
      hi: 'Dominican Republic',
      fr: 'République dominicaine',
      es: 'República Dominicana',
      pt: 'República Dominicana',
      de: 'Dominikanische Republik',
    },
  },
  {
    code: 'EC',
    label: {
      en: 'Ecuador',
      hi: 'Ecuador',
      fr: 'Équateur',
      es: 'Ecuador',
      pt: 'Equador',
      de: 'Ecuador',
    },
  },
  {
    code: 'EG',
    label: { en: 'Egypt', hi: 'Egypt', fr: 'Égypte', es: 'Egipto', pt: 'Egito', de: 'Ägypten' },
  },
  {
    code: 'SV',
    label: {
      en: 'El Salvador',
      hi: 'El Salvador',
      fr: 'Salvador',
      es: 'El Salvador',
      pt: 'El Salvador',
      de: 'El Salvador',
    },
  },
  {
    code: 'GQ',
    label: {
      en: 'Equatorial Guinea',
      hi: 'Equatorial Guinea',
      fr: 'Guinée équatoriale',
      es: 'Guinea Ecuatorial',
      pt: 'Guiné Equatorial',
      de: 'Äquatorialguinea',
    },
  },
  {
    code: 'ER',
    label: {
      en: 'Eritrea',
      hi: 'Eritrea',
      fr: 'Érythrée',
      es: 'Eritrea',
      pt: 'Eritreia',
      de: 'Eritrea',
    },
  },
  {
    code: 'EE',
    label: {
      en: 'Estonia',
      hi: 'Estonia',
      fr: 'Estonie',
      es: 'Estonia',
      pt: 'Estónia',
      de: 'Estland',
    },
  },
  {
    code: 'ET',
    label: {
      en: 'Ethiopia',
      hi: 'Ethiopia',
      fr: 'Éthiopie',
      es: 'Etiopía',
      pt: 'Etiópia',
      de: 'Äthiopien',
    },
  },
  {
    code: 'FK',
    label: {
      en: 'Falkland Islands (Malvinas)',
      hi: 'Falkland Islands (Malvinas)',
      fr: 'Malouines',
      es: 'Islas Malvinas',
      pt: 'Ilhas Malvinas',
      de: 'Falklandinseln',
    },
  },
  {
    code: 'FO',
    label: {
      en: 'Faroe Islands',
      hi: 'Faroe Islands',
      fr: 'Îles Féroé',
      es: 'Islas Feroe',
      pt: 'Ilhas Feroé',
      de: 'Färöer',
    },
  },
  {
    code: 'FJ',
    label: { en: 'Fiji', hi: 'Fiji', fr: 'Fidji', es: 'Fiyi', pt: 'Fiji', de: 'Fidschi' },
  },
  {
    code: 'FI',
    label: {
      en: 'Finland',
      hi: 'Finland',
      fr: 'Finlande',
      es: 'Finlandia',
      pt: 'Finlândia',
      de: 'Finnland',
    },
  },
  {
    code: 'FR',
    label: {
      en: 'France',
      hi: 'France',
      fr: 'France',
      es: 'Francia',
      pt: 'França',
      de: 'Frankreich',
    },
  },
  {
    code: 'GF',
    label: {
      en: 'French Guiana',
      hi: 'French Guiana',
      fr: 'Guyane',
      es: 'Guayana Francesa',
      pt: 'Guiana Francesa',
      de: 'Französisch-Guayana',
    },
  },
  {
    code: 'PF',
    label: {
      en: 'French Polynesia',
      hi: 'French Polynesia',
      fr: 'Polynésie française',
      es: 'Polinesia Francesa',
      pt: 'Polinésia Francesa',
      de: 'Französisch-Polynesien',
    },
  },
  {
    code: 'TF',
    label: {
      en: 'French Southern Territories',
      hi: 'French Southern Territories',
      fr: 'Terres australes et antarctiques françaises',
      es: 'Tierras Australes y Antárticas Francesas',
      pt: 'Terras Austrais e Antárticas Francesas',
      de: 'Französische Süd- und Antarktisgebiete',
    },
  },
  {
    code: 'GA',
    label: { en: 'Gabon', hi: 'Gabon', fr: 'Gabon', es: 'Gabón', pt: 'Gabão', de: 'Gabun' },
  },
  {
    code: 'GM',
    label: { en: 'Gambia', hi: 'Gambia', fr: 'Gambie', es: 'Gambia', pt: 'Gâmbia', de: 'Gambia' },
  },
  {
    code: 'GE',
    label: {
      en: 'Georgia',
      hi: 'Georgia',
      fr: 'Géorgie',
      es: 'Georgia',
      pt: 'Geórgia',
      de: 'Georgien',
    },
  },
  {
    code: 'DE',
    label: {
      en: 'Germany',
      hi: 'Germany',
      fr: 'Allemagne',
      es: 'Alemania',
      pt: 'Alemanha',
      de: 'Deutschland',
    },
  },
  {
    code: 'GH',
    label: { en: 'Ghana', hi: 'Ghana', fr: 'Ghana', es: 'Ghana', pt: 'Gana', de: 'Ghana' },
  },
  {
    code: 'GI',
    label: {
      en: 'Gibraltar',
      hi: 'Gibraltar',
      fr: 'Gibraltar',
      es: 'Gibraltar',
      pt: 'Gibraltar',
      de: 'Gibraltar',
    },
  },
  {
    code: 'GR',
    label: {
      en: 'Greece',
      hi: 'Greece',
      fr: 'Grèce',
      es: 'Grecia',
      pt: 'Grécia',
      de: 'Griechenland',
    },
  },
  {
    code: 'GL',
    label: {
      en: 'Greenland',
      hi: 'Greenland',
      fr: 'Groenland',
      es: 'Groenlandia',
      pt: 'Gronelândia',
      de: 'Grönland',
    },
  },
  {
    code: 'GD',
    label: {
      en: 'Grenada',
      hi: 'Grenada',
      fr: 'Grenade',
      es: 'Granada',
      pt: 'Granada',
      de: 'Grenada',
    },
  },
  {
    code: 'GP',
    label: {
      en: 'Guadeloupe',
      hi: 'Guadeloupe',
      fr: 'Guadeloupe',
      es: 'Guadalupe',
      pt: 'Guadalupe',
      de: 'Guadeloupe',
    },
  },
  { code: 'GU', label: { en: 'Guam', hi: 'Guam', fr: 'Guam', es: 'Guam', pt: 'Guam', de: 'Guam' } },
  {
    code: 'GT',
    label: {
      en: 'Guatemala',
      hi: 'Guatemala',
      fr: 'Guatemala',
      es: 'Guatemala',
      pt: 'Guatemala',
      de: 'Guatemala',
    },
  },
  {
    code: 'GG',
    label: {
      en: 'Guernsey',
      hi: 'Guernsey',
      fr: 'Guernesey',
      es: 'Guernsey',
      pt: 'Guernsey',
      de: 'Guernsey (Kanalinsel)',
    },
  },
  {
    code: 'GN',
    label: { en: 'Guinea', hi: 'Guinea', fr: 'Guinée', es: 'Guinea', pt: 'Guiné', de: 'Guinea' },
  },
  {
    code: 'GW',
    label: {
      en: 'Guinea-Bissau',
      hi: 'Guinea-Bissau',
      fr: 'Guinée-Bissau',
      es: 'Guinea-Bisáu',
      pt: 'Guiné-Bissau',
      de: 'Guinea-Bissau',
    },
  },
  {
    code: 'GY',
    label: { en: 'Guyana', hi: 'Guyana', fr: 'Guyana', es: 'Guyana', pt: 'Guiana', de: 'Guyana' },
  },
  {
    code: 'HT',
    label: { en: 'Haiti', hi: 'Haiti', fr: 'Haïti', es: 'Haití', pt: 'Haiti', de: 'Haiti' },
  },
  {
    code: 'HM',
    label: {
      en: 'Heard Island & Mcdonald Islands',
      hi: 'Heard Island & Mcdonald Islands',
      fr: 'Îles Heard-et-MacDonald',
      es: 'Islas Heard y McDonald',
      pt: 'Ilha Heard e Ilhas McDonald',
      de: 'Heard und McDonaldinseln',
    },
  },
  {
    code: 'VA',
    label: {
      en: 'Holy See (Vatican City State)',
      hi: 'Holy See (Vatican City State)',
      fr: 'Saint-Siège (État de la Cité du Vatican)',
      es: 'Vaticano, Ciudad del',
      pt: 'Vaticano',
      de: 'Vatikanstadt',
    },
  },
  {
    code: 'HN',
    label: {
      en: 'Honduras',
      hi: 'Honduras',
      fr: 'Honduras',
      es: 'Honduras',
      pt: 'Honduras',
      de: 'Honduras',
    },
  },
  {
    code: 'HK',
    label: {
      en: 'Hong Kong',
      hi: 'Hong Kong',
      fr: 'Hong Kong',
      es: 'Hong Kong',
      pt: 'Hong Kong',
      de: 'Hongkong',
    },
  },
  {
    code: 'HU',
    label: {
      en: 'Hungary',
      hi: 'Hungary',
      fr: 'Hongrie',
      es: 'Hungría',
      pt: 'Hungria',
      de: 'Ungarn',
    },
  },
  {
    code: 'IS',
    label: {
      en: 'Iceland',
      hi: 'Iceland',
      fr: 'Islande',
      es: 'Islandia',
      pt: 'Islândia',
      de: 'Island',
    },
  },
  {
    code: 'IN',
    label: { en: 'India', hi: 'India', fr: 'Inde', es: 'India', pt: 'Índia', de: 'Indien' },
  },
  {
    code: 'ID',
    label: {
      en: 'Indonesia',
      hi: 'Indonesia',
      fr: 'Indonésie',
      es: 'Indonesia',
      pt: 'Indonésia',
      de: 'Indonesien',
    },
  },
  {
    code: 'IR',
    label: {
      en: 'Iran}, Islamic Republic Of',
      hi: 'Iran}, Islamic Republic Of',
      fr: 'Iran',
      es: 'Irán',
      pt: 'Irã',
      de: 'Iran',
    },
  },
  {
    code: 'IQ',
    label: { en: 'Iraq', hi: 'Iraq', fr: 'Irak', es: 'Irak', pt: 'Iraque', de: 'Irak' },
  },
  {
    code: 'IE',
    label: {
      en: 'Ireland',
      hi: 'Ireland',
      fr: 'Irlande',
      es: 'Irlanda',
      pt: 'Irlanda',
      de: 'Irland',
    },
  },
  {
    code: 'IM',
    label: {
      en: 'Isle Of Man',
      hi: 'Isle Of Man',
      fr: 'Île de Man',
      es: 'Isla de Man',
      pt: 'Ilha de Man',
      de: 'Insel Man',
    },
  },
  {
    code: 'IL',
    label: { en: 'Israel', hi: 'Israel', fr: 'Israël', es: 'Israel', pt: 'Israel', de: 'Israel' },
  },
  {
    code: 'IT',
    label: { en: 'Italy', hi: 'Italy', fr: 'Italie', es: 'Italia', pt: 'Itália', de: 'Italien' },
  },
  {
    code: 'JM',
    label: {
      en: 'Jamaica',
      hi: 'Jamaica',
      fr: 'Jamaïque',
      es: 'Jamaica',
      pt: 'Jamaica',
      de: 'Jamaika',
    },
  },
  {
    code: 'JP',
    label: { en: 'Japan', hi: 'Japan', fr: 'Japon', es: 'Japón', pt: 'Japão', de: 'Japan' },
  },
  {
    code: 'JE',
    label: {
      en: 'Jersey',
      hi: 'Jersey',
      fr: 'Jersey',
      es: 'Jersey',
      pt: 'Jersey',
      de: 'Jersey (Kanalinsel)',
    },
  },
  {
    code: 'JO',
    label: {
      en: 'Jordan',
      hi: 'Jordan',
      fr: 'Jordanie',
      es: 'Jordania',
      pt: 'Jordânia',
      de: 'Jordanien',
    },
  },
  {
    code: 'KZ',
    label: {
      en: 'Kazakhstan',
      hi: 'Kazakhstan',
      fr: 'Kazakhstan',
      es: 'Kazajistán',
      pt: 'Cazaquistão',
      de: 'Kasachstan',
    },
  },
  {
    code: 'KE',
    label: { en: 'Kenya', hi: 'Kenya', fr: 'Kenya', es: 'Kenia', pt: 'Quênia', de: 'Kenia' },
  },
  {
    code: 'KI',
    label: {
      en: 'Kiribati',
      hi: 'Kiribati',
      fr: 'Kiribati',
      es: 'Kiribati',
      pt: 'Quiribáti',
      de: 'Kiribati',
    },
  },
  {
    code: 'KR',
    label: {
      en: 'Korea (Republic of)',
      hi: 'Korea (Republic of)',
      fr: 'Corée du Sud',
      es: 'Corea del Sur',
      pt: 'Coreia do Sul',
      de: 'Korea, Süd (Südkorea)',
    },
  },
  {
    code: 'KP',
    label: {
      en: "Korea (Democratic People's Republic of)",
      hi: "Korea (Democratic People's Republic of)",
      fr: 'Corée du Nord',
      es: 'Corea del Norte',
      pt: 'Coreia do Norte',
      de: 'Korea, Nord (Nordkorea)',
    },
  },
  {
    code: 'KW',
    label: { en: 'Kuwait', hi: 'Kuwait', fr: 'Koweït', es: 'Kuwait', pt: 'Kuwait', de: 'Kuwait' },
  },
  {
    code: 'KG',
    label: {
      en: 'Kyrgyzstan',
      hi: 'Kyrgyzstan',
      fr: 'Kirghizistan',
      es: 'Kirguistán',
      pt: 'Quirguistão',
      de: 'Kirgisistan',
    },
  },
  {
    code: 'LA',
    label: {
      en: "Lao People's Democratic Republic",
      hi: "Lao People's Democratic Republic",
      fr: 'Laos',
      es: 'Laos',
      pt: 'Laos',
      de: 'Laos',
    },
  },
  {
    code: 'LV',
    label: {
      en: 'Latvia',
      hi: 'Latvia',
      fr: 'Lettonie',
      es: 'Letonia',
      pt: 'Letônia',
      de: 'Lettland',
    },
  },
  {
    code: 'LB',
    label: { en: 'Lebanon', hi: 'Lebanon', fr: 'Liban', es: 'Líbano', pt: 'Líbano', de: 'Libanon' },
  },
  {
    code: 'LS',
    label: {
      en: 'Lesotho',
      hi: 'Lesotho',
      fr: 'Lesotho',
      es: 'Lesoto',
      pt: 'Lesoto',
      de: 'Lesotho',
    },
  },
  {
    code: 'LR',
    label: {
      en: 'Liberia',
      hi: 'Liberia',
      fr: 'Liberia',
      es: 'Liberia',
      pt: 'Libéria',
      de: 'Liberia',
    },
  },
  {
    code: 'LY',
    label: {
      en: 'Libyan Arab Jamahiriya',
      hi: 'Libyan Arab Jamahiriya',
      fr: 'Libye',
      es: 'Libia',
      pt: 'Líbia',
      de: 'Libyen',
    },
  },
  {
    code: 'LI',
    label: {
      en: 'Liechtenstein',
      hi: 'Liechtenstein',
      fr: 'Liechtenstein',
      es: 'Liechtenstein',
      pt: 'Listenstaine',
      de: 'Liechtenstein',
    },
  },
  {
    code: 'LT',
    label: {
      en: 'Lithuania',
      hi: 'Lithuania',
      fr: 'Lituanie',
      es: 'Lituania',
      pt: 'Lituânia',
      de: 'Litauen',
    },
  },
  {
    code: 'LU',
    label: {
      en: 'Luxembourg',
      hi: 'Luxembourg',
      fr: 'Luxembourg',
      es: 'Luxemburgo',
      pt: 'Luxemburgo',
      de: 'Luxemburg',
    },
  },
  {
    code: 'MO',
    label: { en: 'Macao', hi: 'Macao', fr: 'Macao', es: 'Macao', pt: 'Macau', de: 'Macau' },
  },
  {
    code: 'MK',
    label: {
      en: 'Macedonia',
      hi: 'Macedonia',
      fr: 'Macédoine du Nord',
      es: 'Macedonia del Norte',
      pt: 'Macedônia do Norte',
      de: 'Nordmazedonien',
    },
  },
  {
    code: 'MG',
    label: {
      en: 'Madagascar',
      hi: 'Madagascar',
      fr: 'Madagascar',
      es: 'Madagascar',
      pt: 'Madagáscar',
      de: 'Madagaskar',
    },
  },
  {
    code: 'MW',
    label: { en: 'Malawi', hi: 'Malawi', fr: 'Malawi', es: 'Malaui', pt: 'Maláui', de: 'Malawi' },
  },
  {
    code: 'MY',
    label: {
      en: 'Malaysia',
      hi: 'Malaysia',
      fr: 'Malaisie',
      es: 'Malasia',
      pt: 'Malásia',
      de: 'Malaysia',
    },
  },
  {
    code: 'MV',
    label: {
      en: 'Maldives',
      hi: 'Maldives',
      fr: 'Maldives',
      es: 'Maldivas',
      pt: 'Maldivas',
      de: 'Malediven',
    },
  },
  { code: 'ML', label: { en: 'Mali', hi: 'Mali', fr: 'Mali', es: 'Malí', pt: 'Mali', de: 'Mali' } },
  {
    code: 'MT',
    label: { en: 'Malta', hi: 'Malta', fr: 'Malte', es: 'Malta', pt: 'Malta', de: 'Malta' },
  },
  {
    code: 'MH',
    label: {
      en: 'Marshall Islands',
      hi: 'Marshall Islands',
      fr: 'Îles Marshall',
      es: 'Islas Marshall',
      pt: 'Ilhas Marshall',
      de: 'Marshallinseln',
    },
  },
  {
    code: 'MQ',
    label: {
      en: 'Martinique',
      hi: 'Martinique',
      fr: 'Martinique',
      es: 'Martinica',
      pt: 'Martinica',
      de: 'Martinique',
    },
  },
  {
    code: 'MR',
    label: {
      en: 'Mauritania',
      hi: 'Mauritania',
      fr: 'Mauritanie',
      es: 'Mauritania',
      pt: 'Mauritânia',
      de: 'Mauretanien',
    },
  },
  {
    code: 'MU',
    label: {
      en: 'Mauritius',
      hi: 'Mauritius',
      fr: 'Maurice',
      es: 'Mauricio',
      pt: 'Ilhas Maurícias',
      de: 'Mauritius',
    },
  },
  {
    code: 'YT',
    label: {
      en: 'Mayotte',
      hi: 'Mayotte',
      fr: 'Mayotte',
      es: 'Mayotte',
      pt: 'Maiote',
      de: 'Mayotte',
    },
  },
  {
    code: 'MX',
    label: { en: 'Mexico', hi: 'Mexico', fr: 'Mexique', es: 'México', pt: 'México', de: 'Mexiko' },
  },
  {
    code: 'FM',
    label: {
      en: 'Micronesia}, Federated States Of',
      hi: 'Micronesia}, Federated States Of',
      fr: 'États fédérés de Micronésie',
      es: 'Micronesia',
      pt: 'Estados Federados da Micronésia',
      de: 'Mikronesien',
    },
  },
  {
    code: 'MD',
    label: {
      en: 'Moldova',
      hi: 'Moldova',
      fr: 'Moldavie',
      es: 'Moldavia',
      pt: 'Moldávia',
      de: 'Moldau',
    },
  },
  {
    code: 'MC',
    label: { en: 'Monaco', hi: 'Monaco', fr: 'Monaco', es: 'Mónaco', pt: 'Mónaco', de: 'Monaco' },
  },
  {
    code: 'MN',
    label: {
      en: 'Mongolia',
      hi: 'Mongolia',
      fr: 'Mongolie',
      es: 'Mongolia',
      pt: 'Mongólia',
      de: 'Mongolei',
    },
  },
  {
    code: 'ME',
    label: {
      en: 'Montenegro',
      hi: 'Montenegro',
      fr: 'Monténégro',
      es: 'Montenegro',
      pt: 'Montenegro',
      de: 'Montenegro',
    },
  },
  {
    code: 'MS',
    label: {
      en: 'Montserrat',
      hi: 'Montserrat',
      fr: 'Montserrat',
      es: 'Montserrat',
      pt: 'Monserrate',
      de: 'Montserrat',
    },
  },
  {
    code: 'MA',
    label: {
      en: 'Morocco',
      hi: 'Morocco',
      fr: 'Maroc',
      es: 'Marruecos',
      pt: 'Marrocos',
      de: 'Marokko',
    },
  },
  {
    code: 'MZ',
    label: {
      en: 'Mozambique',
      hi: 'Mozambique',
      fr: 'Mozambique',
      es: 'Mozambique',
      pt: 'Moçambique',
      de: 'Mosambik',
    },
  },
  {
    code: 'MM',
    label: {
      en: 'Myanmar',
      hi: 'Myanmar',
      fr: 'Birmanie',
      es: 'Birmania',
      pt: 'Mianmar',
      de: 'Myanmar',
    },
  },
  {
    code: 'NA',
    label: {
      en: 'Namibia',
      hi: 'Namibia',
      fr: 'Namibie',
      es: 'Namibia',
      pt: 'Namíbia',
      de: 'Namibia',
    },
  },
  {
    code: 'NR',
    label: { en: 'Nauru', hi: 'Nauru', fr: 'Nauru', es: 'Nauru', pt: 'Nauru', de: 'Nauru' },
  },
  {
    code: 'NP',
    label: { en: 'Nepal', hi: 'Nepal', fr: 'Népal', es: 'Nepal', pt: 'Nepal', de: 'Nepal' },
  },
  {
    code: 'NL',
    label: {
      en: 'Netherlands',
      hi: 'Netherlands',
      fr: 'Pays-Bas',
      es: 'Países Bajos',
      pt: 'Países Baixos',
      de: 'Niederlande',
    },
  },
  {
    code: 'NC',
    label: {
      en: 'New Caledonia',
      hi: 'New Caledonia',
      fr: 'Nouvelle-Calédonie',
      es: 'Nueva Caledonia',
      pt: 'Nova Caledônia',
      de: 'Neukaledonien',
    },
  },
  {
    code: 'NZ',
    label: {
      en: 'New Zealand',
      hi: 'New Zealand',
      fr: 'Nouvelle-Zélande',
      es: 'Nueva Zelanda',
      pt: 'Nova Zelândia',
      de: 'Neuseeland',
    },
  },
  {
    code: 'NI',
    label: {
      en: 'Nicaragua',
      hi: 'Nicaragua',
      fr: 'Nicaragua',
      es: 'Nicaragua',
      pt: 'Nicarágua',
      de: 'Nicaragua',
    },
  },
  {
    code: 'NE',
    label: { en: 'Niger', hi: 'Niger', fr: 'Niger', es: 'Níger', pt: 'Níger', de: 'Niger' },
  },
  {
    code: 'NG',
    label: {
      en: 'Nigeria',
      hi: 'Nigeria',
      fr: 'Nigeria',
      es: 'Nigeria',
      pt: 'Nigéria',
      de: 'Nigeria',
    },
  },
  { code: 'NU', label: { en: 'Niue', hi: 'Niue', fr: 'Niue', es: 'Niue', pt: 'Niue', de: 'Niue' } },
  {
    code: 'NF',
    label: {
      en: 'Norfolk Island',
      hi: 'Norfolk Island',
      fr: 'Île Norfolk',
      es: 'Isla Norfolk',
      pt: 'Ilha Norfolk',
      de: 'Norfolkinsel',
    },
  },
  {
    code: 'MP',
    label: {
      en: 'Northern Mariana Islands',
      hi: 'Northern Mariana Islands',
      fr: 'Îles Mariannes du Nord',
      es: 'Islas Marianas del Norte',
      pt: 'Marianas Setentrionais',
      de: 'Nördliche Marianen',
    },
  },
  {
    code: 'NO',
    label: {
      en: 'Norway',
      hi: 'Norway',
      fr: 'Norvège',
      es: 'Noruega',
      pt: 'Noruega',
      de: 'Norwegen',
    },
  },
  { code: 'OM', label: { en: 'Oman', hi: 'Oman', fr: 'Oman', es: 'Omán', pt: 'Omã', de: 'Oman' } },
  {
    code: 'PK',
    label: {
      en: 'Pakistan',
      hi: 'Pakistan',
      fr: 'Pakistan',
      es: 'Pakistán',
      pt: 'Paquistão',
      de: 'Pakistan',
    },
  },
  {
    code: 'PW',
    label: { en: 'Palau', hi: 'Palau', fr: 'Palaos', es: 'Palaos', pt: 'Palau', de: 'Palau' },
  },
  {
    code: 'PS',
    label: {
      en: 'Palestinian Territory}, Occupied',
      hi: 'Palestinian Territory}, Occupied',
      fr: 'Palestine',
      es: 'Palestina',
      pt: 'Palestina',
      de: 'Palästina',
    },
  },
  {
    code: 'PA',
    label: { en: 'Panama', hi: 'Panama', fr: 'Panama', es: 'Panamá', pt: 'Panamá', de: 'Panama' },
  },
  {
    code: 'PG',
    label: {
      en: 'Papua New Guinea',
      hi: 'Papua New Guinea',
      fr: 'Papouasie-Nouvelle-Guinée',
      es: 'Papúa Nueva Guinea',
      pt: 'Papua-Nova Guiné',
      de: 'Papua-Neuguinea',
    },
  },
  {
    code: 'PY',
    label: {
      en: 'Paraguay',
      hi: 'Paraguay',
      fr: 'Paraguay',
      es: 'Paraguay',
      pt: 'Paraguai',
      de: 'Paraguay',
    },
  },
  {
    code: 'PE',
    label: { en: 'Peru', hi: 'Peru', fr: 'Pérou', es: 'Perú', pt: 'Peru', de: 'Peru' },
  },
  {
    code: 'PH',
    label: {
      en: 'Philippines',
      hi: 'Philippines',
      fr: 'Philippines',
      es: 'Filipinas',
      pt: 'Filipinas',
      de: 'Philippinen',
    },
  },
  {
    code: 'PN',
    label: {
      en: 'Pitcairn',
      hi: 'Pitcairn',
      fr: 'Îles Pitcairn',
      es: 'Islas Pitcairn',
      pt: 'Pitcairn',
      de: 'Pitcairninseln',
    },
  },
  {
    code: 'PL',
    label: { en: 'Poland', hi: 'Poland', fr: 'Pologne', es: 'Polonia', pt: 'Polónia', de: 'Polen' },
  },
  {
    code: 'PT',
    label: {
      en: 'Portugal',
      hi: 'Portugal',
      fr: 'Portugal',
      es: 'Portugal',
      pt: 'Portugal',
      de: 'Portugal',
    },
  },
  {
    code: 'PR',
    label: {
      en: 'Puerto Rico',
      hi: 'Puerto Rico',
      fr: 'Porto Rico',
      es: 'Puerto Rico',
      pt: 'Porto Rico',
      de: 'Puerto Rico',
    },
  },
  {
    code: 'QA',
    label: { en: 'Qatar', hi: 'Qatar', fr: 'Qatar', es: 'Catar', pt: 'Catar', de: 'Katar' },
  },
  {
    code: 'RE',
    label: {
      en: 'Reunion',
      hi: 'Reunion',
      fr: 'La Réunion',
      es: 'Reunión',
      pt: 'Reunião',
      de: 'Réunion',
    },
  },
  {
    code: 'RO',
    label: {
      en: 'Romania',
      hi: 'Romania',
      fr: 'Roumanie',
      es: 'Rumania',
      pt: 'Roménia',
      de: 'Rumänien',
    },
  },
  {
    code: 'RU',
    label: {
      en: 'Russian Federation',
      hi: 'Russian Federation',
      fr: 'Russie',
      es: 'Rusia',
      pt: 'Rússia',
      de: 'Russland',
    },
  },
  {
    code: 'RW',
    label: { en: 'Rwanda', hi: 'Rwanda', fr: 'Rwanda', es: 'Ruanda', pt: 'Ruanda', de: 'Ruanda' },
  },
  {
    code: 'BL',
    label: {
      en: 'Saint Barthelemy',
      hi: 'Saint Barthelemy',
      fr: 'Saint-Barthélemy',
      es: 'San Bartolomé',
      pt: 'São Bartolomeu',
      de: 'Saint-Barthélemy',
    },
  },
  {
    code: 'SH',
    label: {
      en: 'Saint Helena',
      hi: 'Saint Helena',
      fr: 'Sainte-Hélène, Ascension et Tristan da Cunha',
      es: 'Santa Elena, Ascensión y Tristán de Acuña',
      pt: 'Santa Helena, Ascensão e Tristão da Cunha',
      de: 'St. Helena, Ascension und Tristan da Cunha',
    },
  },
  {
    code: 'KN',
    label: {
      en: 'Saint Kitts And Nevis',
      hi: 'Saint Kitts And Nevis',
      fr: 'Saint-Christophe-et-Niévès',
      es: 'San Cristóbal y Nieves',
      pt: 'São Cristóvão e Neves',
      de: 'St. Kitts und Nevis',
    },
  },
  {
    code: 'LC',
    label: {
      en: 'Saint Lucia',
      hi: 'Saint Lucia',
      fr: 'Sainte-Lucie',
      es: 'Santa Lucía',
      pt: 'Santa Lúcia',
      de: 'St. Lucia',
    },
  },
  {
    code: 'MF',
    label: {
      en: 'Saint Martin (France)',
      hi: 'Saint Martin (France)',
      fr: 'Saint-Martin (France)',
      es: 'San Martín (Francia)',
      pt: 'São Martinho (França)',
      de: 'Saint-Martin (französischer Teil)',
    },
  },
  {
    code: 'SX',
    label: {
      en: 'Saint Martin',
      hi: 'Saint Martin',
      fr: 'Saint-Martin',
      es: 'San Martín',
      pt: 'São Martinho',
      de: 'Sint Maarten',
    },
  },
  {
    code: 'PM',
    label: {
      en: 'Saint Pierre And Miquelon',
      hi: 'Saint Pierre And Miquelon',
      fr: 'Saint-Pierre-et-Miquelon',
      es: 'San Pedro y Miquelón',
      pt: 'São Pedro e Miquelão',
      de: 'Saint-Pierre und Miquelon',
    },
  },
  {
    code: 'VC',
    label: {
      en: 'Saint Vincent And Grenadines',
      hi: 'Saint Vincent And Grenadines',
      fr: 'Saint-Vincent-et-les-Grenadines',
      es: 'San Vicente y las Granadinas',
      pt: 'São Vicente e Granadinas',
      de: 'St. Vincent und die Grenadinen',
    },
  },
  {
    code: 'WS',
    label: { en: 'Samoa', hi: 'Samoa', fr: 'Samoa', es: 'Samoa', pt: 'Samoa', de: 'Samoa' },
  },
  {
    code: 'SM',
    label: {
      en: 'San Marino',
      hi: 'San Marino',
      fr: 'Saint-Marin',
      es: 'San Marino',
      pt: 'San Marino',
      de: 'San Marino',
    },
  },
  {
    code: 'ST',
    label: {
      en: 'Sao Tome And Principe',
      hi: 'Sao Tome And Principe',
      fr: 'Sao Tomé-et-Principe',
      es: 'Santo Tomé y Príncipe',
      pt: 'São Tomé e Príncipe',
      de: 'São Tomé und Príncipe',
    },
  },
  {
    code: 'SA',
    label: {
      en: 'Saudi Arabia',
      hi: 'Saudi Arabia',
      fr: 'Arabie saoudite',
      es: 'Arabia Saudita',
      pt: 'Arábia Saudita',
      de: 'Saudi-Arabien',
    },
  },
  {
    code: 'SN',
    label: {
      en: 'Senegal',
      hi: 'Senegal',
      fr: 'Sénégal',
      es: 'Senegal',
      pt: 'Senegal',
      de: 'Senegal',
    },
  },
  {
    code: 'RS',
    label: { en: 'Serbia', hi: 'Serbia', fr: 'Serbie', es: 'Serbia', pt: 'Sérvia', de: 'Serbien' },
  },
  {
    code: 'SC',
    label: {
      en: 'Seychelles',
      hi: 'Seychelles',
      fr: 'Seychelles',
      es: 'Seychelles',
      pt: 'Seicheles',
      de: 'Seychellen',
    },
  },
  {
    code: 'SL',
    label: {
      en: 'Sierra Leone',
      hi: 'Sierra Leone',
      fr: 'Sierra Leone',
      es: 'Sierra Leona',
      pt: 'Serra Leoa',
      de: 'Sierra Leone',
    },
  },
  {
    code: 'SG',
    label: {
      en: 'Singapore',
      hi: 'Singapore',
      fr: 'Singapour',
      es: 'Singapur',
      pt: 'Singapura',
      de: 'Singapur',
    },
  },
  {
    code: 'SK',
    label: {
      en: 'Slovakia',
      hi: 'Slovakia',
      fr: 'Slovaquie',
      es: 'Eslovaquia',
      pt: 'Eslováquia',
      de: 'Slowakei',
    },
  },
  {
    code: 'SI',
    label: {
      en: 'Slovenia',
      hi: 'Slovenia',
      fr: 'Slovénie',
      es: 'Eslovenia',
      pt: 'Eslovênia',
      de: 'Slowenien',
    },
  },
  {
    code: 'SB',
    label: {
      en: 'Solomon Islands',
      hi: 'Solomon Islands',
      fr: 'Îles Salomon',
      es: 'Islas Salomón',
      pt: 'Ilhas Salomão',
      de: 'Salomonen',
    },
  },
  {
    code: 'SO',
    label: {
      en: 'Somalia',
      hi: 'Somalia',
      fr: 'Somalie',
      es: 'Somalia',
      pt: 'Somália',
      de: 'Somalia',
    },
  },
  {
    code: 'ZA',
    label: {
      en: 'South Africa',
      hi: 'South Africa',
      fr: 'Afrique du Sud',
      es: 'Sudáfrica',
      pt: 'África do Sul',
      de: 'Südafrika',
    },
  },
  {
    code: 'GS',
    label: {
      en: 'South Georgia And Sandwich Isl.',
      hi: 'South Georgia And Sandwich Isl.',
      fr: 'Géorgie du Sud-et-les îles Sandwich du Sud',
      es: 'Islas Georgias del Sur y Sandwich del Sur',
      pt: 'Ilhas Geórgia do Sul e Sandwich do Sul',
      de: 'Südgeorgien und die Südlichen Sandwichinseln',
    },
  },
  {
    code: 'SS',
    label: {
      en: 'South Sudan',
      hi: 'South Sudan',
      fr: 'Soudan du Sud',
      es: 'Sudán del Sur',
      pt: 'Sudão do Sul',
      de: 'Südsudan',
    },
  },
  {
    code: 'ES',
    label: { en: 'Spain', hi: 'Spain', fr: 'Espagne', es: 'España', pt: 'Espanha', de: 'Spanien' },
  },
  {
    code: 'LK',
    label: {
      en: 'Sri Lanka',
      hi: 'Sri Lanka',
      fr: 'Sri Lanka',
      es: 'Sri Lanka',
      pt: 'Seri Lanca',
      de: 'Sri Lanka',
    },
  },
  {
    code: 'SD',
    label: { en: 'Sudan', hi: 'Sudan', fr: 'Soudan', es: 'Sudán', pt: 'Sudão', de: 'Sudan' },
  },
  {
    code: 'SR',
    label: {
      en: 'Suriname',
      hi: 'Suriname',
      fr: 'Suriname',
      es: 'Surinam',
      pt: 'Suriname',
      de: 'Suriname',
    },
  },
  {
    code: 'SJ',
    label: {
      en: 'Svalbard And Jan Mayen',
      hi: 'Svalbard And Jan Mayen',
      fr: 'Svalbard et île Jan Mayen',
      es: 'Svalbard y Jan Mayen',
      pt: 'Esvalbarde e Jan Mayen',
      de: 'Spitzbergen und Jan Mayen',
    },
  },
  {
    code: 'SZ',
    label: {
      en: 'Swaziland',
      hi: 'Swaziland',
      fr: 'Eswatini',
      es: 'Suazilandia',
      pt: 'Essuatíni',
      de: 'Eswatini',
    },
  },
  {
    code: 'SE',
    label: { en: 'Sweden', hi: 'Sweden', fr: 'Suède', es: 'Suecia', pt: 'Suécia', de: 'Schweden' },
  },
  {
    code: 'CH',
    label: {
      en: 'Switzerland',
      hi: 'Switzerland',
      fr: 'Suisse',
      es: 'Suiza',
      pt: 'Suíça',
      de: 'Schweiz',
    },
  },
  {
    code: 'SY',
    label: {
      en: 'Syrian Arab Republic',
      hi: 'Syrian Arab Republic',
      fr: 'Syrie',
      es: 'Siria',
      pt: 'Síria',
      de: 'Syrien',
    },
  },
  {
    code: 'TW',
    label: {
      en: 'Taiwan',
      hi: 'Taiwan',
      fr: 'Taïwan (République de Chine)',
      es: 'Taiwán (República de China)',
      pt: 'Taiwan',
      de: 'China, Republik',
    },
  },
  {
    code: 'TJ',
    label: {
      en: 'Tajikistan',
      hi: 'Tajikistan',
      fr: 'Tadjikistan',
      es: 'Tayikistán',
      pt: 'Tajiquistão',
      de: 'Tadschikistan',
    },
  },
  {
    code: 'TZ',
    label: {
      en: 'Tanzania',
      hi: 'Tanzania',
      fr: 'Tanzanie',
      es: 'Tanzania',
      pt: 'Tanzânia',
      de: 'Tansania',
    },
  },
  {
    code: 'TH',
    label: {
      en: 'Thailand',
      hi: 'Thailand',
      fr: 'Thaïlande',
      es: 'Tailandia',
      pt: 'Tailândia',
      de: 'Thailand',
    },
  },
  {
    code: 'TL',
    label: {
      en: 'Timor-Leste',
      hi: 'Timor-Leste',
      fr: 'Timor oriental',
      es: 'Timor Oriental',
      pt: 'Timor-Leste',
      de: 'Osttimor',
    },
  },
  { code: 'TG', label: { en: 'Togo', hi: 'Togo', fr: 'Togo', es: 'Togo', pt: 'Togo', de: 'Togo' } },
  {
    code: 'TK',
    label: {
      en: 'Tokelau',
      hi: 'Tokelau',
      fr: 'Tokelau',
      es: 'Tokelau',
      pt: 'Toquelau',
      de: 'Tokelau',
    },
  },
  {
    code: 'TO',
    label: { en: 'Tonga', hi: 'Tonga', fr: 'Tonga', es: 'Tonga', pt: 'Tonga', de: 'Tonga' },
  },
  {
    code: 'TT',
    label: {
      en: 'Trinidad And Tobago',
      hi: 'Trinidad And Tobago',
      fr: 'Trinité-et-Tobago',
      es: 'Trinidad y Tobago',
      pt: 'Trinidad e Tobago',
      de: 'Trinidad und Tobago',
    },
  },
  {
    code: 'TN',
    label: {
      en: 'Tunisia',
      hi: 'Tunisia',
      fr: 'Tunisie',
      es: 'Túnez',
      pt: 'Tunísia',
      de: 'Tunesien',
    },
  },
  {
    code: 'TR',
    label: {
      en: 'Turkey',
      hi: 'Turkey',
      fr: 'Turquie',
      es: 'Turquía',
      pt: 'Turquia',
      de: 'Türkei',
    },
  },
  {
    code: 'TM',
    label: {
      en: 'Turkmenistan',
      hi: 'Turkmenistan',
      fr: 'Turkménistan',
      es: 'Turkmenistán',
      pt: 'Turcomenistão',
      de: 'Turkmenistan',
    },
  },
  {
    code: 'TC',
    label: {
      en: 'Turks And Caicos Islands',
      hi: 'Turks And Caicos Islands',
      fr: 'Îles Turques-et-Caïques',
      es: 'Islas Turcas y Caicos',
      pt: 'Turcas e Caicos',
      de: 'Turks- und Caicosinseln',
    },
  },
  {
    code: 'TV',
    label: { en: 'Tuvalu', hi: 'Tuvalu', fr: 'Tuvalu', es: 'Tuvalu', pt: 'Tuvalu', de: 'Tuvalu' },
  },
  {
    code: 'UG',
    label: { en: 'Uganda', hi: 'Uganda', fr: 'Ouganda', es: 'Uganda', pt: 'Uganda', de: 'Uganda' },
  },
  {
    code: 'UA',
    label: {
      en: 'Ukraine',
      hi: 'Ukraine',
      fr: 'Ukraine',
      es: 'Ucrania',
      pt: 'Ucrânia',
      de: 'Ukraine',
    },
  },
  {
    code: 'AE',
    label: {
      en: 'United Arab Emirates',
      hi: 'United Arab Emirates',
      fr: 'Émirats arabes unis',
      es: 'Emiratos Árabes Unidos',
      pt: 'Emirados Árabes Unidos',
      de: 'Vereinigte Arabische Emirate',
    },
  },
  {
    code: 'GB',
    label: {
      en: 'United Kingdom',
      hi: 'United Kingdom',
      fr: 'Royaume-Uni',
      es: 'Reino Unido',
      pt: 'Reino Unido',
      de: 'Vereinigtes Königreich',
    },
  },
  {
    code: 'US',
    label: {
      en: 'United States',
      hi: 'United States',
      fr: 'États-Unis',
      es: 'Estados Unidos',
      pt: 'Estados Unidos',
      de: 'Vereinigte Staaten',
    },
  },
  {
    code: 'UM',
    label: {
      en: 'United States Outlying Islands',
      hi: 'United States Outlying Islands',
      fr: 'Îles mineures éloignées des États-Unis',
      es: 'Islas Ultramarinas Menores de los Estados Unidos',
      pt: 'Ilhas Menores Distantes dos Estados Unidos',
      de: 'United States Minor Outlying Islands',
    },
  },
  {
    code: 'UY',
    label: {
      en: 'Uruguay',
      hi: 'Uruguay',
      fr: 'Uruguay',
      es: 'Uruguay',
      pt: 'Uruguai',
      de: 'Uruguay',
    },
  },
  {
    code: 'UZ',
    label: {
      en: 'Uzbekistan',
      hi: 'Uzbekistan',
      fr: 'Ouzbékistan',
      es: 'Uzbekistán',
      pt: 'Uzbequistão',
      de: 'Usbekistan',
    },
  },
  {
    code: 'VU',
    label: {
      en: 'Vanuatu',
      hi: 'Vanuatu',
      fr: 'Vanuatu',
      es: 'Vanuatu',
      pt: 'Vanuatu',
      de: 'Vanuatu',
    },
  },
  {
    code: 'VE',
    label: {
      en: 'Venezuela',
      hi: 'Venezuela',
      fr: 'Venezuela',
      es: 'Venezuela',
      pt: 'Venezuela',
      de: 'Venezuela',
    },
  },
  {
    code: 'VN',
    label: {
      en: 'Vietnam',
      hi: 'Vietnam',
      fr: 'Viêt Nam',
      es: 'Vietnam',
      pt: 'Vietname',
      de: 'Vietnam',
    },
  },
  {
    code: 'VG',
    label: {
      en: 'Virgin Islands}, British',
      hi: 'Virgin Islands}, British',
      fr: 'Îles Vierges britanniques',
      es: 'Islas Vírgenes Británicas',
      pt: 'Ilhas Virgens Britânicas',
      de: 'Britische Jungferninseln',
    },
  },
  {
    code: 'VI',
    label: {
      en: 'Virgin Islands}, U.S.',
      hi: 'Virgin Islands}, U.S.',
      fr: 'Îles Vierges des États-Unis',
      es: 'Islas Vírgenes de los Estados Unidos',
      pt: 'Ilhas Virgens Americanas',
      de: 'Amerikanische Jungferninseln',
    },
  },
  {
    code: 'WF',
    label: {
      en: 'Wallis And Futuna',
      hi: 'Wallis And Futuna',
      fr: 'Wallis-et-Futuna',
      es: 'Wallis y Futuna',
      pt: 'Wallis e Futuna',
      de: 'Wallis und Futuna',
    },
  },
  {
    code: 'EH',
    label: {
      en: 'Western Sahara',
      hi: 'Western Sahara',
      fr: 'République arabe sahraouie démocratique',
      es: 'República Árabe Saharaui Democrática',
      pt: 'Saara Ocidental',
      de: 'Westsahara',
    },
  },
  {
    code: 'YE',
    label: { en: 'Yemen', hi: 'Yemen', fr: 'Yémen', es: 'Yemen', pt: 'Iêmen', de: 'Jemen' },
  },
  {
    code: 'ZM',
    label: { en: 'Zambia', hi: 'Zambia', fr: 'Zambie', es: 'Zambia', pt: 'Zâmbia', de: 'Sambia' },
  },
  {
    code: 'ZW',
    label: {
      en: 'Zimbabwe',
      hi: 'Zimbabwe',
      fr: 'Zimbabwe',
      es: 'Zimbabue',
      pt: 'Zimbábue',
      de: 'Simbabwe',
    },
  },
];
