export const CREATE_USER_ALREADY_EXISTS = 'CREATE_USER_ALREADY_EXISTS';
export const CREATE_USER_WEAK_PASSWORD = 'CREATE_USER_WEAK_PASSWORD';
export const CREATE_USER_INVALID_EMAIL = 'CREATE_USER_INVALID_EMAIL';
export const UPDATE_USER_ALREADY_EXISTS = 'UPDATE_USER_ALREADY_EXISTS';

// MFA/2FA errors
export const MFA_REQUIRES_RECENT_LOGIN = 'MFA_REQUIRES_RECENT_LOGIN';
export const MFA_RECAPTCHA_ERROR = 'MFA_RECAPTCHA_ERROR';
