import React from 'react';

async function generateSiteMap({ locales }: any) {
  // Currently static due to timeout issues using dynamic generation
  // TODO: Investigate dynamic generation after app router refactor
  return `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://bloom.chayn.co</loc>
</url>
<url>
<loc>https://bloom.chayn.co/meet-the-team</loc>
</url>
<url>
<loc>https://bloom.chayn.co/messaging</loc>
</url>
<url>
<loc>https://bloom.chayn.co/activities</loc>
</url>
<url>
<loc>https://bloom.chayn.co/grounding</loc>
</url>
<url>
<loc>https://bloom.chayn.co/subscription/whatsapp</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/the-social-context-of-image-based-abuse-and-victim-blaming</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/the-social-context-of-image-based-abuse-and-victim-blaming</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/the-social-context-of-image-based-abuse-and-victim-blaming</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/the-social-context-of-image-based-abuse-and-victim-blaming</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/the-social-context-of-image-based-abuse-and-victim-blaming</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/the-social-context-of-image-based-abuse-and-victim-blaming</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma/the-self-and-sexual-violence</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma/the-self-and-sexual-violence</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma/the-self-and-sexual-violence</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma/the-self-and-sexual-violence</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma/the-self-and-sexual-violence</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma/the-self-and-sexual-violence</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/introduction-and-what-you-should-know</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/introduction-and-what-you-should-know</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/introduction-and-what-you-should-know</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/introduction-and-what-you-should-know</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/introduction-and-what-you-should-know</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/introduction-and-what-you-should-know</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/what-is-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/what-is-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/what-is-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/what-is-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/what-is-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/what-is-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/what-is-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/what-is-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/what-is-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/what-is-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/what-is-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/what-is-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/what-are-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/what-are-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/what-are-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/what-are-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/what-are-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/what-are-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/naming-abuse-and-coercive-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/naming-abuse-and-coercive-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/naming-abuse-and-coercive-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/naming-abuse-and-coercive-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/naming-abuse-and-coercive-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/naming-abuse-and-coercive-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/unpacking-and-processing-our-emotions</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/unpacking-and-processing-our-emotions</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/unpacking-and-processing-our-emotions</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/unpacking-and-processing-our-emotions</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/unpacking-and-processing-our-emotions</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/unpacking-and-processing-our-emotions</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma/mythologies-of-the-patriarchy</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma/mythologies-of-the-patriarchy</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma/mythologies-of-the-patriarchy</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma/mythologies-of-the-patriarchy</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma/mythologies-of-the-patriarchy</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma/mythologies-of-the-patriarchy</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/fear-in-the-body</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/fear-in-the-body</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/fear-in-the-body</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/fear-in-the-body</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/fear-in-the-body</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/fear-in-the-body</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/culture-patriarchy-and-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/culture-patriarchy-and-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/culture-patriarchy-and-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/culture-patriarchy-and-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/culture-patriarchy-and-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/culture-patriarchy-and-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/the-trauma-response</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/the-trauma-response</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/the-trauma-response</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/the-trauma-response</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/the-trauma-response</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/the-trauma-response</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/emotional-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/emotional-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/emotional-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/emotional-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/emotional-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/emotional-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/anger</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/anger</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/anger</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/anger</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/anger</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/anger</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/fear</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/fear</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/fear</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/fear</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/fear</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/fear</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma/predatory-behaviour</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma/predatory-behaviour</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma/predatory-behaviour</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma/predatory-behaviour</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma/predatory-behaviour</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma/predatory-behaviour</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/adverse-childhood-experiences</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/adverse-childhood-experiences</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/adverse-childhood-experiences</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/adverse-childhood-experiences</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/adverse-childhood-experiences</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/adverse-childhood-experiences</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/fear-in-the-body</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/fear-in-the-body</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/fear-in-the-body</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/fear-in-the-body</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/fear-in-the-body</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/fear-in-the-body</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/trauma-bonding-is-addictive</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/trauma-bonding-is-addictive</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/trauma-bonding-is-addictive</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/trauma-bonding-is-addictive</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/trauma-bonding-is-addictive</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/trauma-bonding-is-addictive</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/physical-and-sexual-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/physical-and-sexual-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/physical-and-sexual-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/physical-and-sexual-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/physical-and-sexual-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/physical-and-sexual-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/guilt-and-shame</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/guilt-and-shame</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/guilt-and-shame</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/guilt-and-shame</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/guilt-and-shame</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/guilt-and-shame</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/shame-and-guilt</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/shame-and-guilt</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/shame-and-guilt</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/shame-and-guilt</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/shame-and-guilt</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/shame-and-guilt</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/systemic-forms-of-oppression</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/systemic-forms-of-oppression</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/systemic-forms-of-oppression</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/systemic-forms-of-oppression</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/systemic-forms-of-oppression</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/systemic-forms-of-oppression</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma/enthusiastic-consent</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma/enthusiastic-consent</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma/enthusiastic-consent</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma/enthusiastic-consent</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma/enthusiastic-consent</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma/enthusiastic-consent</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/toxic-vs-healthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/toxic-vs-healthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/toxic-vs-healthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/toxic-vs-healthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/toxic-vs-healthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/toxic-vs-healthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/restoring-safety-and-rebuilding-trust</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/restoring-safety-and-rebuilding-trust</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/restoring-safety-and-rebuilding-trust</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/restoring-safety-and-rebuilding-trust</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/restoring-safety-and-rebuilding-trust</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/restoring-safety-and-rebuilding-trust</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma/telling-someone-about-the-assault</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma/telling-someone-about-the-assault</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma/telling-someone-about-the-assault</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma/telling-someone-about-the-assault</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma/telling-someone-about-the-assault</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma/telling-someone-about-the-assault</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/betrayal-and-anger</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/betrayal-and-anger</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/betrayal-and-anger</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/betrayal-and-anger</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/betrayal-and-anger</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/betrayal-and-anger</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/body-image</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/body-image</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/body-image</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/body-image</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/body-image</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/body-image</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/narcissism-attachment-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/narcissism-attachment-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/narcissism-attachment-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/narcissism-attachment-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/narcissism-attachment-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/narcissism-attachment-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/understanding-our-responses-to-image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/understanding-our-responses-to-image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/understanding-our-responses-to-image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/understanding-our-responses-to-image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/understanding-our-responses-to-image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/understanding-our-responses-to-image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/the-art-of-resilience</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/the-art-of-resilience</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/the-art-of-resilience</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/the-art-of-resilience</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/the-art-of-resilience</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/the-art-of-resilience</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/recovery-tools</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/recovery-tools</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/recovery-tools</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/recovery-tools</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/recovery-tools</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/recovery-tools</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/sexuality-and-desire</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/sexuality-and-desire</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/sexuality-and-desire</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/sexuality-and-desire</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/sexuality-and-desire</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/sexuality-and-desire</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/positive-coping-mechanisms</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/positive-coping-mechanisms</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/positive-coping-mechanisms</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/positive-coping-mechanisms</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/positive-coping-mechanisms</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/positive-coping-mechanisms</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/short-term-boundaries-the-early-stages</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/short-term-boundaries-the-early-stages</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/short-term-boundaries-the-early-stages</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/short-term-boundaries-the-early-stages</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/short-term-boundaries-the-early-stages</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/short-term-boundaries-the-early-stages</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/sex-after-assault</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/sex-after-assault</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/sex-after-assault</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/sex-after-assault</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/sex-after-assault</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/sex-after-assault</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-our-body-and-body-image</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-our-body-and-body-image</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-our-body-and-body-image</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-our-body-and-body-image</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-our-body-and-body-image</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-our-body-and-body-image</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/power-control-and-patriarchy</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/power-control-and-patriarchy</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/power-control-and-patriarchy</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/power-control-and-patriarchy</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/power-control-and-patriarchy</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/power-control-and-patriarchy</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/the-cycle-of-coercive-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/the-cycle-of-coercive-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/the-cycle-of-coercive-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/the-cycle-of-coercive-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/the-cycle-of-coercive-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/the-cycle-of-coercive-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/long-term-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/long-term-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/long-term-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/long-term-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/long-term-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/long-term-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-sense-of-self-and-identity</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-sense-of-self-and-identity</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-sense-of-self-and-identity</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-sense-of-self-and-identity</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-sense-of-self-and-identity</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-sense-of-self-and-identity</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/unhelpful-coping-mechanisms</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/unhelpful-coping-mechanisms</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/unhelpful-coping-mechanisms</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/unhelpful-coping-mechanisms</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/unhelpful-coping-mechanisms</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/unhelpful-coping-mechanisms</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/live-session-storylines</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/live-session-storylines</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/live-session-storylines</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/live-session-storylines</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/live-session-storylines</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/live-session-storylines</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/anger-is-not-the-same-as-aggression</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/anger-is-not-the-same-as-aggression</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/anger-is-not-the-same-as-aggression</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/anger-is-not-the-same-as-aggression</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/anger-is-not-the-same-as-aggression</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/anger-is-not-the-same-as-aggression</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-technology</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-technology</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-technology</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-technology</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-technology</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-technology</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/moving-forward-with-hope</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/moving-forward-with-hope</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/moving-forward-with-hope</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/moving-forward-with-hope</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/moving-forward-with-hope</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/moving-forward-with-hope</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/guilt-grief-and-letting-go</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/guilt-grief-and-letting-go</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/guilt-grief-and-letting-go</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/guilt-grief-and-letting-go</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/guilt-grief-and-letting-go</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/guilt-grief-and-letting-go</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/staying-leaving-coping-and-what-happens-next</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/staying-leaving-coping-and-what-happens-next</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/staying-leaving-coping-and-what-happens-next</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/staying-leaving-coping-and-what-happens-next</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/staying-leaving-coping-and-what-happens-next</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/staying-leaving-coping-and-what-happens-next</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/creating-a-safer-environment-if-you-stay-and-exit-strategies</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/creating-a-safer-environment-if-you-stay-and-exit-strategies</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/creating-a-safer-environment-if-you-stay-and-exit-strategies</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/creating-a-safer-environment-if-you-stay-and-exit-strategies</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/creating-a-safer-environment-if-you-stay-and-exit-strategies</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/creating-a-safer-environment-if-you-stay-and-exit-strategies</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/building-healthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/building-healthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/building-healthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/building-healthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/building-healthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/building-healthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/final-reflections</loc>
</url>
<url>
<loc>https://bloom.chayn.co/conversations/stolen-faces-how-fake-images-leave-real-scars</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/conversations/stolen-faces-how-fake-images-leave-real-scars</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/conversations/stolen-faces-how-fake-images-leave-real-scars</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/conversations/stolen-faces-how-fake-images-leave-real-scars</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/conversations/stolen-faces-how-fake-images-leave-real-scars</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/conversations/stolen-faces-how-fake-images-leave-real-scars</loc>
</url>
<url>
<loc>https://bloom.chayn.co/conversations/crossing-the-line-how-technology-turns-into-a-tool-of-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/conversations/crossing-the-line-how-technology-turns-into-a-tool-of-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/conversations/crossing-the-line-how-technology-turns-into-a-tool-of-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/conversations/crossing-the-line-how-technology-turns-into-a-tool-of-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/conversations/crossing-the-line-how-technology-turns-into-a-tool-of-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/conversations/crossing-the-line-how-technology-turns-into-a-tool-of-control</loc>
</url>
<url>
<loc>https://bloom.chayn.co/conversations/selling-dreams-the-dark-side-of-digital-influence</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/conversations/selling-dreams-the-dark-side-of-digital-influence</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/conversations/selling-dreams-the-dark-side-of-digital-influence</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/conversations/selling-dreams-the-dark-side-of-digital-influence</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/conversations/selling-dreams-the-dark-side-of-digital-influence</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/conversations/selling-dreams-the-dark-side-of-digital-influence</loc>
</url>
<url>
<loc>https://bloom.chayn.co/shorts/what-are-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/shorts/what-are-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/shorts/what-are-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/shorts/what-are-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/shorts/what-are-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/shorts/what-are-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/shorts/healing-from-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/shorts/healing-from-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/shorts/healing-from-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/shorts/healing-from-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/shorts/healing-from-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/shorts/healing-from-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/shorts/healthy-vs-unhealthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/shorts/healthy-vs-unhealthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/shorts/healthy-vs-unhealthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/shorts/healthy-vs-unhealthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/shorts/healthy-vs-unhealthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/shorts/healthy-vs-unhealthy-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/shorts/sex-after-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/shorts/sex-after-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/shorts/sex-after-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/shorts/sex-after-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/shorts/sex-after-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/shorts/sex-after-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/shorts/what-is-assertiveness-</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/shorts/what-is-assertiveness-</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/shorts/what-is-assertiveness-</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/shorts/what-is-assertiveness-</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/shorts/what-is-assertiveness-</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/shorts/what-is-assertiveness-</loc>
</url>
<url>
<loc>https://bloom.chayn.co/shorts/rigid-vs-relaxed-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/shorts/rigid-vs-relaxed-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/shorts/rigid-vs-relaxed-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/shorts/rigid-vs-relaxed-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/shorts/rigid-vs-relaxed-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/shorts/rigid-vs-relaxed-boundaries</loc>
</url>
<url>
<loc>https://bloom.chayn.co/shorts/fear</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/shorts/fear</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/shorts/fear</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/shorts/fear</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/shorts/fear</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/shorts/fear</loc>
</url>
<url>
<loc>https://bloom.chayn.co/shorts/online-safety</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/shorts/online-safety</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/shorts/online-safety</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/shorts/online-safety</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/shorts/online-safety</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/shorts/online-safety</loc>
</url>
<url>
<loc>https://bloom.chayn.co/shorts/the-social-context-of-image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/shorts/the-social-context-of-image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/shorts/the-social-context-of-image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/shorts/the-social-context-of-image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/shorts/the-social-context-of-image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/shorts/the-social-context-of-image-based-abuse</loc>
</url>
<url>
<loc>https://bloom.chayn.co/shorts/society-patriarchy-and-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/shorts/society-patriarchy-and-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/shorts/society-patriarchy-and-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/shorts/society-patriarchy-and-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/shorts/society-patriarchy-and-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/shorts/society-patriarchy-and-sexual-trauma</loc>
</url>
<url>
<loc>https://bloom.chayn.co/shorts/dating-boundaries-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/shorts/dating-boundaries-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/shorts/dating-boundaries-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/shorts/dating-boundaries-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/shorts/dating-boundaries-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/shorts/dating-boundaries-and-relationships</loc>
</url>
<url>
<loc>https://bloom.chayn.co/shorts/enthusiastic-consent</loc>
</url>
<url>
<loc>https://bloom.chayn.co/es/shorts/enthusiastic-consent</loc>
</url>
<url>
<loc>https://bloom.chayn.co/hi/shorts/enthusiastic-consent</loc>
</url>
<url>
<loc>https://bloom.chayn.co/fr/shorts/enthusiastic-consent</loc>
</url>
<url>
<loc>https://bloom.chayn.co/pt/shorts/enthusiastic-consent</loc>
</url>
<url>
<loc>https://bloom.chayn.co/de/shorts/enthusiastic-consent</loc>
</url>
</urlset>
    `;
}

const SiteMap: React.FC = () => {
  // getServerSideProps will do the heavy lifting
  return null;
};

export async function getServerSideProps({ locales, res }: any) {
  // We generate the XML sitemap with the courses data
  const sitemap = await generateSiteMap({ locales });

  res.setHeader('Content-Type', 'text/xml');
  // we send the XML to the browser
  res.write(sitemap);
  res.end();

  return {
    props: {},
  };
}

export default SiteMap;
