import React from 'react';
import { getStaticPaths as getConversationsStaticPaths } from './conversations/[slug]';
import { getStaticPaths as getShortsStaticPaths } from './shorts/[slug]';

async function generateSiteMap({ locales }: any) {
  /* get url paths for dynamically generated courses using getStaticPaths */

  const conversations = (await getConversationsStaticPaths({ locales })).paths;
  const shorts = (await getShortsStaticPaths({ locales })).paths;

  /* courses and sessions are currently static to avoid timeout issues for getting all dynamic paths */
  // const courses = (await getCoursesStaticPaths({ locales })).paths;
  // const sessions = (await getSessionsStaticPaths({ locales })).paths;
  // Add the code below to the xml return to use dynamic courses again
  // ${courses
  //   .map((course: { locale: string; params: { slug: string } }) => {
  //     const locale = course.locale !== 'en' ? `/${course.locale}` : '';
  //     return `
  //             <url>
  //                 <loc>${`https://bloom.chayn.co${locale}/courses/${course.params.slug}`}</loc>
  //             </url>
  //         `;
  //   })
  //   .join('')}
  // ${sessions
  //   .map((course: { locale: string; params: { slug: string; sessionSlug: string } }) => {
  //     const locale = course.locale !== 'en' ? `/${course.locale}` : '';
  //     return `
  //             <url>
  //                 <loc>${`https://bloom.chayn.co${locale}/courses/${course.params.slug}/${course.params.sessionSlug}`}</loc>
  //             </url>
  //         `;
  //   })
  //   .join('')}

  return `<?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
        <url>
            <loc>https://bloom.chayn.co</loc>
        </url>
        <url>
            <loc>https://bloom.chayn.co/meet-the-team</loc>
        </url>
        <url>
            <loc>https://bloom.chayn.co/messaging</loc>
        </url>
        <url>
            <loc>https://bloom.chayn.co/activities</loc>
        </url>
        <url>
            <loc>https://bloom.chayn.co/grounding</loc>
        </url>
        <url>
            <loc>https://bloom.chayn.co/subscription/whatsapp</loc>
        </url>
        <url>
            <loc>https://bloom.chayn.co/courses</loc>
        </url>
        <url>
            <loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/the-social-context-of-image-based-abuse-and-victim-blaming</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/the-social-context-of-image-based-abuse-and-victim-blaming</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/the-social-context-of-image-based-abuse-and-victim-blaming</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/the-social-context-of-image-based-abuse-and-victim-blaming</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/the-social-context-of-image-based-abuse-and-victim-blaming</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/the-social-context-of-image-based-abuse-and-victim-blaming</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma/the-self-and-sexual-violence</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma/the-self-and-sexual-violence</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma/the-self-and-sexual-violence</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma/the-self-and-sexual-violence</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma/the-self-and-sexual-violence</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma/the-self-and-sexual-violence</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/introduction-and-what-you-should-know</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/introduction-and-what-you-should-know</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/introduction-and-what-you-should-know</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/introduction-and-what-you-should-know</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/introduction-and-what-you-should-know</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/introduction-and-what-you-should-know</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/what-is-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/what-is-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/what-is-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/what-is-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/what-is-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/what-is-sexual-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/what-is-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/what-is-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/what-is-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/what-is-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/what-is-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/what-is-trauma</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/what-are-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/what-are-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/what-are-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/what-are-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/what-are-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/what-are-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/naming-abuse-and-coercive-control</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/naming-abuse-and-coercive-control</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/naming-abuse-and-coercive-control</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/naming-abuse-and-coercive-control</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/naming-abuse-and-coercive-control</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/naming-abuse-and-coercive-control</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/unpacking-and-processing-our-emotions</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/unpacking-and-processing-our-emotions</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/unpacking-and-processing-our-emotions</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/unpacking-and-processing-our-emotions</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/unpacking-and-processing-our-emotions</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/unpacking-and-processing-our-emotions</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma/mythologies-of-the-patriarchy</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma/mythologies-of-the-patriarchy</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma/mythologies-of-the-patriarchy</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma/mythologies-of-the-patriarchy</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma/mythologies-of-the-patriarchy</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma/mythologies-of-the-patriarchy</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/fear-in-the-body</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/fear-in-the-body</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/fear-in-the-body</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/fear-in-the-body</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/fear-in-the-body</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/fear-in-the-body</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/culture-patriarchy-and-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/culture-patriarchy-and-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/culture-patriarchy-and-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/culture-patriarchy-and-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/culture-patriarchy-and-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/culture-patriarchy-and-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/the-trauma-response</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/the-trauma-response</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/the-trauma-response</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/the-trauma-response</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/the-trauma-response</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/the-trauma-response</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/emotional-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/emotional-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/emotional-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/emotional-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/emotional-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/emotional-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/anger</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/anger</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/anger</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/anger</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/anger</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/anger</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/fear</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/fear</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/fear</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/fear</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/fear</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/fear</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma/predatory-behaviour</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma/predatory-behaviour</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma/predatory-behaviour</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma/predatory-behaviour</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma/predatory-behaviour</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma/predatory-behaviour</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/adverse-childhood-experiences</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/adverse-childhood-experiences</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/adverse-childhood-experiences</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/adverse-childhood-experiences</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/adverse-childhood-experiences</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/adverse-childhood-experiences</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/fear-in-the-body</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/fear-in-the-body</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/fear-in-the-body</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/fear-in-the-body</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/fear-in-the-body</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/fear-in-the-body</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/trauma-bonding-is-addictive</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/trauma-bonding-is-addictive</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/trauma-bonding-is-addictive</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/trauma-bonding-is-addictive</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/trauma-bonding-is-addictive</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/trauma-bonding-is-addictive</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/physical-and-sexual-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/physical-and-sexual-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/physical-and-sexual-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/physical-and-sexual-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/physical-and-sexual-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/physical-and-sexual-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/guilt-and-shame</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/guilt-and-shame</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/guilt-and-shame</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/guilt-and-shame</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/guilt-and-shame</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/guilt-and-shame</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/shame-and-guilt</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/shame-and-guilt</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/shame-and-guilt</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/shame-and-guilt</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/shame-and-guilt</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/shame-and-guilt</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/systemic-forms-of-oppression</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/systemic-forms-of-oppression</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/systemic-forms-of-oppression</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/systemic-forms-of-oppression</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/systemic-forms-of-oppression</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/systemic-forms-of-oppression</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma/enthusiastic-consent</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma/enthusiastic-consent</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma/enthusiastic-consent</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma/enthusiastic-consent</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma/enthusiastic-consent</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma/enthusiastic-consent</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/toxic-vs-healthy-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/toxic-vs-healthy-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/toxic-vs-healthy-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/toxic-vs-healthy-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/toxic-vs-healthy-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/toxic-vs-healthy-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/restoring-safety-and-rebuilding-trust</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/restoring-safety-and-rebuilding-trust</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/restoring-safety-and-rebuilding-trust</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/restoring-safety-and-rebuilding-trust</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/restoring-safety-and-rebuilding-trust</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/restoring-safety-and-rebuilding-trust</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma/telling-someone-about-the-assault</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma/telling-someone-about-the-assault</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma/telling-someone-about-the-assault</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma/telling-someone-about-the-assault</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma/telling-someone-about-the-assault</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma/telling-someone-about-the-assault</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/betrayal-and-anger</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/betrayal-and-anger</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/betrayal-and-anger</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/betrayal-and-anger</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/betrayal-and-anger</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/betrayal-and-anger</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/body-image</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/body-image</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/body-image</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/body-image</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/body-image</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/body-image</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/narcissism-attachment-and-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/narcissism-attachment-and-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/narcissism-attachment-and-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/narcissism-attachment-and-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/narcissism-attachment-and-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/narcissism-attachment-and-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/understanding-our-responses-to-image-based-abuse</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/understanding-our-responses-to-image-based-abuse</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/understanding-our-responses-to-image-based-abuse</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/understanding-our-responses-to-image-based-abuse</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/understanding-our-responses-to-image-based-abuse</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/understanding-our-responses-to-image-based-abuse</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/the-art-of-resilience</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/the-art-of-resilience</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/the-art-of-resilience</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/the-art-of-resilience</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/the-art-of-resilience</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/the-art-of-resilience</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/recovery-tools</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/recovery-tools</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/recovery-tools</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/recovery-tools</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/recovery-tools</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/recovery-tools</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/sexuality-and-desire</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/sexuality-and-desire</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/sexuality-and-desire</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/sexuality-and-desire</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/sexuality-and-desire</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/sexuality-and-desire</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/society-patriarchy-and-sexual-trauma/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/society-patriarchy-and-sexual-trauma/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/society-patriarchy-and-sexual-trauma/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/society-patriarchy-and-sexual-trauma/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/society-patriarchy-and-sexual-trauma/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/society-patriarchy-and-sexual-trauma/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/image-based-abuse</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/image-based-abuse</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/image-based-abuse</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/image-based-abuse</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/image-based-abuse</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/image-based-abuse</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/positive-coping-mechanisms</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/positive-coping-mechanisms</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/positive-coping-mechanisms</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/positive-coping-mechanisms</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/positive-coping-mechanisms</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/positive-coping-mechanisms</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/short-term-boundaries-the-early-stages</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/short-term-boundaries-the-early-stages</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/short-term-boundaries-the-early-stages</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/short-term-boundaries-the-early-stages</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/short-term-boundaries-the-early-stages</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/short-term-boundaries-the-early-stages</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/sex-after-assault</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/sex-after-assault</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/sex-after-assault</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/sex-after-assault</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/sex-after-assault</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/sex-after-assault</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-our-body-and-body-image</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-our-body-and-body-image</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-our-body-and-body-image</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-our-body-and-body-image</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-our-body-and-body-image</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-our-body-and-body-image</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/power-control-and-patriarchy</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/power-control-and-patriarchy</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/power-control-and-patriarchy</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/power-control-and-patriarchy</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/power-control-and-patriarchy</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/power-control-and-patriarchy</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/the-cycle-of-coercive-control</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/the-cycle-of-coercive-control</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/the-cycle-of-coercive-control</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/the-cycle-of-coercive-control</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/the-cycle-of-coercive-control</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/the-cycle-of-coercive-control</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/dating-boundaries-and-relationships/long-term-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/dating-boundaries-and-relationships/long-term-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/dating-boundaries-and-relationships/long-term-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/dating-boundaries-and-relationships/long-term-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/dating-boundaries-and-relationships/long-term-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/dating-boundaries-and-relationships/long-term-boundaries</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-sense-of-self-and-identity</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-sense-of-self-and-identity</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-sense-of-self-and-identity</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-sense-of-self-and-identity</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-sense-of-self-and-identity</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-sense-of-self-and-identity</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/unhelpful-coping-mechanisms</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/unhelpful-coping-mechanisms</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/unhelpful-coping-mechanisms</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/unhelpful-coping-mechanisms</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/unhelpful-coping-mechanisms</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/unhelpful-coping-mechanisms</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/healing-from-sexual-trauma/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/healing-from-sexual-trauma/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/healing-from-sexual-trauma/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/healing-from-sexual-trauma/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/healing-from-sexual-trauma/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/healing-from-sexual-trauma/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/live-session-storylines</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/live-session-storylines</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/live-session-storylines</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/live-session-storylines</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/live-session-storylines</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/live-session-storylines</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/anger-is-not-the-same-as-aggression</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/anger-is-not-the-same-as-aggression</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/anger-is-not-the-same-as-aggression</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/anger-is-not-the-same-as-aggression</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/anger-is-not-the-same-as-aggression</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/anger-is-not-the-same-as-aggression</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-technology</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-technology</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-technology</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-technology</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-technology</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/healing-our-relationship-with-technology</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/image-based-abuse-and-rebuilding-ourselves/moving-forward-with-hope</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/image-based-abuse-and-rebuilding-ourselves/moving-forward-with-hope</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/image-based-abuse-and-rebuilding-ourselves/moving-forward-with-hope</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/image-based-abuse-and-rebuilding-ourselves/moving-forward-with-hope</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/image-based-abuse-and-rebuilding-ourselves/moving-forward-with-hope</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/image-based-abuse-and-rebuilding-ourselves/moving-forward-with-hope</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/reclaiming-resilience-in-your-trauma-story/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/reclaiming-resilience-in-your-trauma-story/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/reclaiming-resilience-in-your-trauma-story/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/reclaiming-resilience-in-your-trauma-story/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/reclaiming-resilience-in-your-trauma-story/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/reclaiming-resilience-in-your-trauma-story/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/guilt-grief-and-letting-go</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/guilt-grief-and-letting-go</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/guilt-grief-and-letting-go</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/guilt-grief-and-letting-go</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/guilt-grief-and-letting-go</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/guilt-grief-and-letting-go</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/staying-leaving-coping-and-what-happens-next</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/staying-leaving-coping-and-what-happens-next</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/staying-leaving-coping-and-what-happens-next</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/staying-leaving-coping-and-what-happens-next</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/staying-leaving-coping-and-what-happens-next</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/staying-leaving-coping-and-what-happens-next</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/creating-a-safer-environment-if-you-stay-and-exit-strategies</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/creating-a-safer-environment-if-you-stay-and-exit-strategies</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/creating-a-safer-environment-if-you-stay-and-exit-strategies</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/creating-a-safer-environment-if-you-stay-and-exit-strategies</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/creating-a-safer-environment-if-you-stay-and-exit-strategies</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/creating-a-safer-environment-if-you-stay-and-exit-strategies</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/building-healthy-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/building-healthy-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/building-healthy-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/building-healthy-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/building-healthy-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/building-healthy-relationships</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/es/courses/recovering-from-toxic-and-abusive-relationships/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/hi/courses/recovering-from-toxic-and-abusive-relationships/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/fr/courses/recovering-from-toxic-and-abusive-relationships/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/pt/courses/recovering-from-toxic-and-abusive-relationships/final-reflections</loc>
        </url>
        <url>
          <loc>https://bloom.chayn.co/de/courses/recovering-from-toxic-and-abusive-relationships/final-reflections</loc>
        </url>
        ${conversations
          .map((conversation: { locale: string; params: { slug: string } }) => {
            const locale = conversation.locale !== 'en' ? `/${conversation.locale}` : '';
            return `
                    <url>
                        <loc>${`https://bloom.chayn.co${locale}/conversations/${conversation.params.slug}`}</loc>
                    </url>
                `;
          })
          .join('')}
        ${shorts
          .map((short: { locale: string; params: { slug: string } }) => {
            const locale = short.locale !== 'en' ? `/${short.locale}` : '';
            return `
                    <url>
                        <loc>${`https://bloom.chayn.co${locale}/shorts/${short.params.slug}`}</loc>
                    </url>
                `;
          })
          .join('')}
    </urlset>
    `;
}

const SiteMap: React.FC = () => {
  // getServerSideProps will do the heavy lifting
  return null;
};

export async function getServerSideProps({ locales, res }: any) {
  // We generate the XML sitemap with the courses data
  const sitemap = await generateSiteMap({ locales });

  res.setHeader('Content-Type', 'text/xml');
  // we send the XML to the browser
  res.write(sitemap);
  res.end();

  return {
    props: {},
  };
}

export default SiteMap;
