# This workflow comments on PRs opened by first time contributors.
# Reminds first timer contributors to associate their PR with an issue and follow the guidelines.

name: First Interaction PR Comment

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "First time contributors to Chayn, please make sure that this PR is linked to an issue you are assigned! Read the CONTRIBUTING.md file for more details."
