name: Merge onto Develop Pipeline
# TODO rename to deploy to staging

on:
  push:
    branches:
      - develop

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_STAGING_APP}} # Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: 'develop'

  cypress-run:
    name: Cypress e2e tets
    needs: deploy-to-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run cypress
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          spec: cypress/**/*.cy.tsx
          headed: false
        env:
          NEXT_PUBLIC_ROLLBAR_ENV: CI
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_ROLLBAR_CLIENT_TOKEN: ${{ secrets.NEXT_PUBLIC_ROLLBAR_CLIENT_TOKEN }}
          NEXT_PUBLIC_STORYBLOK_TOKEN: ${{ secrets.NEXT_PUBLIC_STORYBLOK_TOKEN }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          CYPRESS_BASE_URL: 'https://bloom-frontend-staging.herokuapp.com/' # runs cypress against staging
          CYPRESS_mail-slurp-api-key: ${{secrets.MAIL_SLURP_API_KEY}}
          CYPRESS_inbox-id: ${{secrets.MAILBOX_INBOX_ID}}
          CYPRESS_reset-pwd-content-email: ${{secrets.RESET_PWD_CONTENT_EMAIL}}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-pr-to-main:
    name: Create PR to deploy to production
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const pullRequestResponse = await github.rest.pulls.list({
              owner,
              repo,
              base: 'main'
            });

            console.log(pullRequestResponse); // TODO remove once we know this is working and why
            if (pullRequestResponse.status === 200 && pullRequestResponse.data.length === 0) {
              const result = await github.rest.pulls.create({
                title: 'Merge Develop onto Main',
                owner,
                repo,
                head: 'develop',
                base: 'main',
                body: [
                  'This PR is auto-generated by',
                  '[actions/github-script](https://github.com/actions/github-script).'
                ].join('\n')
              });
            }
