name: Prescan PR

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [develop]

permissions:
  contents: read

jobs:
  pre-build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}nm
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Use NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Run linting
        run: yarn lint

      - name: Run type checks
        run: yarn type-check
        continue-on-error: true

      - name: View PR author 
        run: |
          run: |
            if [ ${{ github.event.pull_request.user.login }} == 'kyleecodes' ]; then
              echo "${{ github.event.pull_request.user.login }} - approved"
              exit 0
            else
              echo "${{ github.event.pull_request.user.login }} - Not approved"
              exit 1
            fi
