name: Prescan PR

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [develop]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}nm
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Use NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Run linting
        run: yarn lint

      - name: Run type checks
        run: yarn type-check
        continue-on-error: true

      - name: View PR author
        id: view-pr-author
        env:
          TEAM_MEMBER: ${{ github.event.pull_request.user.login == 'kyleecodes' }}
        run: |
          if [ $TEAM_MEMBER = true ]; 
            echo "This PR is opened by a team member."
            exit 0
          else
            echo "This PR is opened by a non-team member."
            exit 1
          fi

      # - name: The PR author is not a team member
      #   if: ${{ failure() && steps.view-pr-author.conclusion == 'failure' }}
      #   run: echo "PR author is not a team member - checks failed"
