name: Run tests from fork
on:
  pull_request_target:
    types: [opened, synchronize]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    # Get user permission of workflow triggering actor, return true or false 
      - name: Get User Permission
        id: checkAccess
        # Action used: https://github.com/actions-cool/check-user-permission
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.triggering_actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Check user permission from previous step, exit if false
      - name: Check User Permission
        if: steps.checkAccess.outputs.require-result == 'false'
        run: |
          echo "${{ github.triggering_actor }} does not have permissions to run workflows on this repo."
          echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
          echo "Job originally triggered by ${{ github.actor }}"
          exit 1
    # Checkout PR code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # This is dangerous without the first access check
          ref: ${{  github.event.pull_request.head.sha }}
      - name: Run tests
        run: |
          if [[ "x${{ secrets.SECRET_TEST }}" == "xval" ]]; then
            echo "Access to secrets"
          else
            echo "No access to secrets"
            exit 1
          fi
